using HomeServices.Domain.Catalog;
using HomeServices.Domain.Localization;

namespace HomeServices.Infrastructure.Persistence.Configurations;

// Work items with starter labour prices for Yerevan (AMD per unit), generated from tools/catalog-seed/work_items.csv.
// Edit the CSV and run tools/catalog-seed/work_items.py instead of changing this file by hand.
internal static partial class CatalogSeed
{
    /// <summary>Work items in display order within each subcategory.</summary>
    internal static readonly (Guid Id, string CategorySlug, string Slug, WorkUnit Unit, WorkSurface Surface, int PriceMin, int PriceTypical, int PriceMax, LocalizedText Name)[] WorkItems =
    [
        // construction-turnkey-houses
        (new("ae301c42-d86f-5017-be47-5202a1a1784c"), "construction-turnkey-houses", "house-shell-construction", WorkUnit.SquareMeter, WorkSurface.None, 25000, 35000, 50000, Text("Տան սև կարկասի կառուցում", "Строительство коробки дома", "House shell construction", "بناء الهيكل الأساسي للمنزل", "سفت‌کاری و ساخت اسکلت خانه", "घर का ढांचा निर्माण")),
        (new("c48d089e-8ff4-56c0-a0da-cdfc80fcf0ea"), "construction-turnkey-houses", "house-interior-finishing", WorkUnit.SquareMeter, WorkSurface.Floor, 20000, 30000, 45000, Text("Տան ներքին հարդարում", "Внутренняя отделка дома", "Interior finishing of a house", "التشطيبات الداخلية للمنزل", "نازک‌کاری داخلی خانه", "घर की इंटीरियर फ़िनिशिंग")),
        // construction-foundations
        (new("11f94366-d67c-5b96-9557-0fd3e2f2fe16"), "construction-foundations", "strip-foundation", WorkUnit.CubicMeter, WorkSurface.None, 15000, 22000, 30000, Text("Ժապավենային հիմք", "Ленточный фундамент", "Strip foundation", "أساس شريطي", "فونداسیون نواری", "स्ट्रिप फ़ाउंडेशन")),
        (new("efa8ce87-9889-5148-b931-2d731c5de842"), "construction-foundations", "slab-foundation", WorkUnit.CubicMeter, WorkSurface.None, 12000, 18000, 25000, Text("Սալային հիմք", "Плитный фундамент", "Slab foundation", "أساس لبشة", "فونداسیون گسترده (رادیه)", "स्लैब फ़ाउंडेशन")),
        (new("1e16be33-9310-565e-ac9a-39e5b61f2bcd"), "construction-foundations", "foundation-waterproofing", WorkUnit.SquareMeter, WorkSurface.Wall, 2000, 3000, 5000, Text("Հիմքի ջրամեկուսացում", "Гидроизоляция фундамента", "Foundation waterproofing", "عزل الأساسات ضد الماء", "عایق‌کاری رطوبتی فونداسیون", "फ़ाउंडेशन वॉटरप्रूफ़िंग")),
        // construction-masonry
        (new("3eb7b553-1553-5def-a143-8ec7724184e1"), "construction-masonry", "tuff-wall-masonry", WorkUnit.SquareMeter, WorkSurface.Wall, 5000, 7000, 10000, Text("Տուֆով պատի շարում", "Кладка стен из туфа", "Tuff stone wall laying", "بناء جدران من حجر التوف", "دیوارچینی با سنگ توف", "टफ़ पत्थर की दीवार चिनाई")),
        (new("87772963-047d-5804-b786-2d4729276926"), "construction-masonry", "block-wall-masonry", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4500, 6500, Text("Բետոնե բլոկով պատի շարում", "Кладка стен из бетонных блоков", "Concrete block wall laying", "بناء جدران من البلوك الخرساني", "دیوارچینی با بلوک بتنی", "कंक्रीट ब्लॉक की दीवार चिनाई")),
        (new("43078562-03ff-5f41-833d-1e20669a09f8"), "construction-masonry", "brick-wall-masonry", WorkUnit.SquareMeter, WorkSurface.Wall, 4000, 6000, 9000, Text("Աղյուսով պատի շարում", "Кладка стен из кирпича", "Brick wall laying", "بناء جدران من الطوب", "آجرچینی دیوار", "ईंट की दीवार चिनाई")),
        (new("d5721113-01db-5910-b298-e1c817a16172"), "construction-masonry", "light-block-partition", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4000, 6000, Text("Թեթև բլոկից միջնապատ", "Перегородка из лёгких блоков", "Light block partition wall", "جدار فاصل من البلوك الخفيف", "دیوار جداکننده با بلوک سبک", "हल्के ब्लॉक की पार्टिशन दीवार")),
        // construction-concrete
        (new("328694fe-d1f5-57ff-a668-0a92e9612ff1"), "construction-concrete", "concrete-pouring", WorkUnit.CubicMeter, WorkSurface.None, 10000, 15000, 25000, Text("Բետոնի լցում", "Заливка бетона", "Concrete pouring", "صب الخرسانة", "بتن‌ریزی", "कंक्रीट ढलाई")),
        (new("a5d0cad7-41d1-5fbc-b408-2539808eadf7"), "construction-concrete", "reinforced-concrete-slab", WorkUnit.CubicMeter, WorkSurface.None, 20000, 30000, 45000, Text("Երկաթբետոնե սալ", "Железобетонная плита", "Reinforced concrete slab", "بلاطة خرسانية مسلحة", "دال بتن مسلح", "आरसीसी स्लैब")),
        (new("d5252b14-5c85-5b1d-aed0-134a04d1c7aa"), "construction-concrete", "formwork-installation", WorkUnit.SquareMeter, WorkSurface.None, 2500, 4000, 6000, Text("Կաղապարամածի տեղադրում", "Монтаж опалубки", "Formwork installation", "تركيب القوالب (الشدة)", "قالب‌بندی", "शटरिंग का काम")),
        // construction-extensions
        (new("f511787d-6481-5974-afa7-3d7215fd4e79"), "construction-extensions", "extension-shell", WorkUnit.SquareMeter, WorkSurface.Floor, 25000, 35000, 50000, Text("Կցակառույց կամ լրացուցիչ հարկ, սև կարկաս", "Пристройка или надстройка этажа, коробка", "Extension or extra floor, shell work", "توسعة أو طابق إضافي، أعمال الهيكل", "توسعه یا طبقه اضافه، سفت‌کاری", "एक्सटेंशन या अतिरिक्त मंज़िल, ढांचा कार्य")),
        (new("ac5ed7bc-84e1-51bb-be50-a6016f82f672"), "construction-extensions", "loggia-extension", WorkUnit.SquareMeter, WorkSurface.Floor, 20000, 30000, 45000, Text("Պատշգամբի կամ լոջիայի ընդլայնում", "Расширение балкона или лоджии", "Balcony or loggia extension", "توسيع الشرفة أو اللوجيا", "توسعه بالکن یا لاجیا", "बालकनी या लॉजिया का विस्तार")),
        // construction-outbuildings
        (new("c68e061c-25e3-5455-937f-a7bc9abd4e5d"), "construction-outbuildings", "garage-construction", WorkUnit.SquareMeter, WorkSurface.Floor, 20000, 30000, 45000, Text("Ավտոտնակի կառուցում", "Строительство гаража", "Garage construction", "بناء مرآب", "ساخت گاراژ", "गैराज निर्माण")),
        (new("fd9489a6-259a-5749-8771-9b8bdaa0241f"), "construction-outbuildings", "outbuilding-construction", WorkUnit.SquareMeter, WorkSurface.Floor, 15000, 22000, 35000, Text("Պահեստի կամ օժանդակ շինության կառուցում", "Строительство сарая или хозпостройки", "Shed or outbuilding construction", "بناء سقيفة أو ملحق", "ساخت انباری یا سازه جانبی", "शेड या आउटहाउस निर्माण")),
        // construction-stairs
        (new("cc173b43-e129-5840-8969-4356f262d830"), "construction-stairs", "concrete-stairs", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 20000, Text("Բետոնե աստիճաններ, 1 աստիճանի համար", "Бетонная лестница, за ступень", "Concrete stairs, per step", "درج خرساني، لكل درجة", "پله بتنی، به ازای هر پله", "कंक्रीट की सीढ़ियां, प्रति स्टेप")),
        (new("17e79f95-a374-5f5b-8f92-504bad7e28cc"), "construction-stairs", "stair-step-cladding", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Աստիճանների երեսպատում սալիկով կամ քարով", "Облицовка ступеней плиткой или камнем", "Stair step cladding with tiles or stone", "تكسية درجات السلم بالبلاط أو الحجر", "روکش پله با کاشی یا سنگ", "सीढ़ी के स्टेप पर टाइल या पत्थर लगाना")),
        // construction-reinforcement
        (new("190f0976-6591-56ed-b048-6d56bd6c4ec2"), "construction-reinforcement", "wall-mesh-reinforcement", WorkUnit.SquareMeter, WorkSurface.Wall, 6000, 9000, 14000, Text("Պատի ամրացում մետաղական ցանցով և տորկրետով", "Усиление стен металлической сеткой и торкретированием", "Wall reinforcement with steel mesh and shotcrete", "تدعيم الجدران بشبك فولاذي وخرسانة مقذوفة", "تقویت دیوار با مش فولادی و شاتکریت", "स्टील मेश और शॉटक्रीट से दीवार की मज़बूती")),
        (new("721b0e22-bc64-54e2-af5a-259452434d84"), "construction-reinforcement", "wall-opening-reinforcement", WorkUnit.Piece, WorkSurface.None, 40000, 70000, 120000, Text("Պատում նոր բացվածքի ամրացում", "Усиление нового проёма в стене", "Reinforcing a new wall opening", "تدعيم فتحة جديدة في الجدار", "تقویت بازشوی جدید در دیوار", "दीवार में नए ओपनिंग की मज़बूती")),
        (new("9a539425-85a3-50fc-b611-79f19ff8c732"), "construction-reinforcement", "crack-injection-repair", WorkUnit.RunningMeter, WorkSurface.None, 3000, 5000, 8000, Text("Ճաքերի վերանորոգում ներարկման եղանակով", "Ремонт трещин методом инъектирования", "Crack repair by injection", "إصلاح الشقوق بالحقن", "ترمیم ترک با تزریق", "इंजेक्शन से दरारों की मरम्मत")),
        // renovation-apartment
        (new("4573c505-081c-59e4-937e-075e9734ea21"), "renovation-apartment", "apartment-renovation-premium", WorkUnit.SquareMeter, WorkSurface.Floor, 25000, 35000, 55000, Text("Բնակարանի ամբողջական վերանորոգում, պրեմիում", "Полный ремонт квартиры, премиум", "Full apartment renovation, premium", "تجديد شامل للشقة، فئة ممتازة", "بازسازی کامل آپارتمان، لوکس", "पूरे अपार्टमेंट का रेनोवेशन, प्रीमियम")),
        (new("78011376-8c39-5738-b4ff-f66dcec6f9f9"), "renovation-apartment", "apartment-renovation-standard", WorkUnit.SquareMeter, WorkSurface.Floor, 15000, 22000, 30000, Text("Բնակարանի ամբողջական վերանորոգում, ստանդարտ", "Полный ремонт квартиры, стандарт", "Full apartment renovation, standard", "تجديد شامل للشقة، فئة قياسية", "بازسازی کامل آپارتمان، استاندارد", "पूरे अपार्टमेंट का रेनोवेशन, स्टैंडर्ड")),
        // renovation-cosmetic
        (new("5a226555-88b8-5ec0-b86d-da4d1a95942b"), "renovation-cosmetic", "cosmetic-renovation", WorkUnit.SquareMeter, WorkSurface.Floor, 6000, 9000, 14000, Text("Կոսմետիկ վերանորոգում (ներկ, պաստառ, հատակ)", "Косметический ремонт (покраска, обои, пол)", "Cosmetic renovation (paint, wallpaper, floor)", "تجديد تجميلي (دهان، ورق جدران، أرضيات)", "بازسازی سطحی (رنگ، کاغذدیواری، کف)", "कॉस्मेटिक रेनोवेशन (पेंट, वॉलपेपर, फ़र्श)")),
        (new("368c3c4b-155d-5e28-bc50-39cb2fa346dc"), "renovation-cosmetic", "wall-patching", WorkUnit.SquareMeter, WorkSurface.Wall, 1500, 2500, 4000, Text("Պատերի կարկատում և վերանորոգում", "Заделка и ремонт стен", "Patching and repairing walls", "ترميم وإصلاح الجدران", "لکه‌گیری و تعمیر دیوار", "दीवारों की पैचिंग और मरम्मत")),
        // renovation-plastering
        (new("207cb7c7-d957-5a76-9276-a3e3f3d7b5a5"), "renovation-plastering", "wall-plastering", WorkUnit.SquareMeter, WorkSurface.Wall, 2500, 3500, 5000, Text("Պատերի սվաղում", "Штукатурка стен", "Wall plastering", "لياسة الجدران", "گچ‌کاری دیوار", "दीवार पर प्लास्टर")),
        (new("7e3d6c11-3fb0-5d80-89ca-588b7f9c86d3"), "renovation-plastering", "ceiling-plastering", WorkUnit.SquareMeter, WorkSurface.Ceiling, 3000, 4000, 6000, Text("Առաստաղի սվաղում", "Штукатурка потолка", "Ceiling plastering", "لياسة الأسقف", "گچ‌کاری سقف", "छत पर प्लास्टर")),
        (new("37ee7081-3836-5679-80b6-3ada931a2ce8"), "renovation-plastering", "wall-putty", WorkUnit.SquareMeter, WorkSurface.Wall, 1500, 2200, 3500, Text("Պատերի շպատլյովկա, վերջնական շերտ", "Финишная шпаклёвка стен", "Wall putty, finishing coat", "معجون الجدران، طبقة نهائية", "بتونه‌کاری دیوار، لایه نهایی", "दीवार पर पुट्टी, फ़िनिशिंग कोट")),
        (new("c65f69d0-3e04-51de-b41a-563899d92ab6"), "renovation-plastering", "ceiling-putty", WorkUnit.SquareMeter, WorkSurface.Ceiling, 1800, 2500, 4000, Text("Առաստաղի շպատլյովկա, վերջնական շերտ", "Финишная шпаклёвка потолка", "Ceiling putty, finishing coat", "معجون الأسقف، طبقة نهائية", "بتونه‌کاری سقف، لایه نهایی", "छत पर पुट्टी, फ़िनिशिंग कोट")),
        (new("2f925487-c521-527f-a0f7-f543f3467baa"), "renovation-plastering", "corner-bead-installation", WorkUnit.RunningMeter, WorkSurface.None, 500, 800, 1200, Text("Ներկարարական անկյունակների տեղադրում", "Установка малярных уголков", "Corner bead installation", "تركيب زوايا حماية الحواف", "نصب نبشی گوشه دیوار", "कॉर्नर बीड लगाना")),
        // renovation-painting
        (new("0b6f1ab4-07bb-5314-ae38-1477f56b0dcf"), "renovation-painting", "wall-painting", WorkUnit.SquareMeter, WorkSurface.Wall, 1000, 1500, 2500, Text("Պատերի ներկում, երկու շերտ", "Покраска стен в два слоя", "Wall painting, two coats", "دهان الجدران، طبقتان", "رنگ‌آمیزی دیوار، دو لایه", "दीवार पेंटिंग, दो कोट")),
        (new("cbaa0c31-b390-5955-81ec-bb4d7fffc1a3"), "renovation-painting", "ceiling-painting", WorkUnit.SquareMeter, WorkSurface.Ceiling, 1200, 1800, 2800, Text("Առաստաղի ներկում, երկու շերտ", "Покраска потолка в два слоя", "Ceiling painting, two coats", "دهان الأسقف، طبقتان", "رنگ‌آمیزی سقف، دو لایه", "छत पेंटिंग, दो कोट")),
        (new("94c3315b-80b8-5def-9f5d-10120cefdbe0"), "renovation-painting", "surface-priming", WorkUnit.SquareMeter, WorkSurface.Wall, 300, 500, 800, Text("Մակերեսների գրունտում", "Грунтовка поверхностей", "Priming surfaces", "طلاء الأسطح بالبرايمر", "آستر زدن سطوح", "सतहों पर प्राइमर लगाना")),
        (new("e672be9e-3dc0-5aac-a074-5de3106381ae"), "renovation-painting", "door-painting", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 20000, Text("Դռան ներկում", "Покраска двери", "Door painting", "دهان الأبواب", "رنگ‌آمیزی در", "दरवाज़े की पेंटिंग")),
        (new("9c8b1566-a45e-53d7-9a17-e818753d477e"), "renovation-painting", "radiator-painting", WorkUnit.Piece, WorkSurface.None, 4000, 6000, 10000, Text("Ռադիատորի ներկում", "Покраска радиатора", "Radiator painting", "دهان المشعات", "رنگ‌آمیزی رادیاتور", "रेडिएटर की पेंटिंग")),
        // renovation-wallpaper
        (new("6eb0879f-09b7-5bb5-87c7-0a22439df06e"), "renovation-wallpaper", "wallpaper-hanging", WorkUnit.SquareMeter, WorkSurface.Wall, 1500, 2000, 3000, Text("Պաստառապատում", "Поклейка обоев", "Wallpaper hanging", "تركيب ورق الجدران", "نصب کاغذدیواری", "वॉलपेपर लगाना")),
        (new("16427d1b-6a25-526d-93ad-66572c8d957e"), "renovation-wallpaper", "wallpaper-removal", WorkUnit.SquareMeter, WorkSurface.Wall, 500, 800, 1200, Text("Հին պաստառի հեռացում", "Снятие старых обоев", "Old wallpaper removal", "إزالة ورق الجدران القديم", "برداشتن کاغذدیواری قدیمی", "पुराना वॉलपेपर हटाना")),
        (new("596e6125-3a31-5272-9260-752f488cc20c"), "renovation-wallpaper", "glass-fibre-wallpaper", WorkUnit.SquareMeter, WorkSurface.Wall, 1500, 2200, 3200, Text("Ներկվող ապակեպաստառ", "Стеклообои под покраску", "Paintable glass-fibre wallpaper", "ورق جدران من الألياف الزجاجية قابل للدهان", "کاغذدیواری فایبرگلاس قابل رنگ", "पेंट होने वाला ग्लास-फ़ाइबर वॉलपेपर")),
        // renovation-tiling
        (new("be10c7ad-bf9a-5cfc-a52d-7784414dc88e"), "renovation-tiling", "wall-tiling", WorkUnit.SquareMeter, WorkSurface.Wall, 5000, 7000, 10000, Text("Պատերի սալիկապատում", "Укладка плитки на стены", "Wall tiling", "تبليط الجدران", "کاشی‌کاری دیوار", "दीवार पर टाइल लगाना")),
        (new("0f04b279-2a8f-561a-a8c8-897c916fda8e"), "renovation-tiling", "floor-tiling", WorkUnit.SquareMeter, WorkSurface.Floor, 5000, 6500, 9000, Text("Հատակի սալիկապատում", "Укладка плитки на пол", "Floor tiling", "تبليط الأرضيات", "کاشی‌کاری کف", "फ़र्श पर टाइल लगाना")),
        (new("64adf4ac-a385-5e05-8f43-40985d7780ab"), "renovation-tiling", "large-format-tiling", WorkUnit.SquareMeter, WorkSurface.Floor, 8000, 11000, 16000, Text("Խոշոր չափսի կերամոգրանիտե սալերի տեղադրում", "Укладка крупноформатного керамогранита", "Large-format porcelain slab laying", "تركيب ألواح البورسلين كبيرة الحجم", "نصب اسلب پرسلان با ابعاد بزرگ", "बड़े साइज़ की पोर्सिलेन स्लैब लगाना")),
        (new("ac954ec4-01b7-54ab-b4c8-46e7d6dac4e4"), "renovation-tiling", "mosaic-laying", WorkUnit.SquareMeter, WorkSurface.Wall, 8000, 12000, 18000, Text("Մոզաիկայի տեղադրում", "Укладка мозаики", "Mosaic laying", "تركيب الموزاييك", "نصب کاشی موزاییک", "मोज़ेक लगाना")),
        (new("ddc04332-baca-5399-b4b8-4a6d002e14f6"), "renovation-tiling", "tile-grouting", WorkUnit.SquareMeter, WorkSurface.Wall, 1000, 1500, 2500, Text("Սալիկի կարերի լցում և նորացում", "Затирка и перезатирка швов плитки", "Tile grouting and re-grouting", "ترويب البلاط وإعادة ترويبه", "بندکشی و ترمیم بندکشی کاشی", "टाइल ग्राउटिंग और री-ग्राउटिंग")),
        (new("f9852146-0725-52c0-9475-6e162bd52508"), "renovation-tiling", "tile-removal", WorkUnit.SquareMeter, WorkSurface.Wall, 1000, 1500, 2500, Text("Հին սալիկի ապամոնտաժում", "Демонтаж старой плитки", "Old tile removal", "إزالة البلاط القديم", "برداشتن کاشی قدیمی", "पुरानी टाइल हटाना")),
        (new("be51713a-de35-5ecf-b7a1-ded73872b4cf"), "renovation-tiling", "tile-skirting", WorkUnit.RunningMeter, WorkSurface.None, 1000, 1500, 2500, Text("Սալիկից պլինտուս", "Плинтус из плитки", "Tile skirting", "نعلات من البلاط", "قرنیز کاشی", "टाइल स्कर्टिंग")),
        // renovation-flooring
        (new("55408b7a-abf8-57d2-a11b-5dbf916473b8"), "renovation-flooring", "laminate-laying", WorkUnit.SquareMeter, WorkSurface.Floor, 1500, 2000, 3000, Text("Լամինատի տեղադրում", "Укладка ламината", "Laminate laying", "تركيب أرضيات اللامينيت", "نصب کفپوش لمینت", "लैमिनेट फ़्लोरिंग लगाना")),
        (new("c8b55d98-d000-5c4b-aafb-3a806577b4d3"), "renovation-flooring", "parquet-laying", WorkUnit.SquareMeter, WorkSurface.Floor, 3000, 4500, 7000, Text("Մանրահատակի տեղադրում", "Укладка паркета", "Parquet laying", "تركيب الباركيه", "نصب پارکت", "पार्केट फ़्लोरिंग लगाना")),
        (new("8bf47f28-ef4f-540d-a711-90a391b0f732"), "renovation-flooring", "parquet-sanding", WorkUnit.SquareMeter, WorkSurface.Floor, 3000, 4500, 6500, Text("Մանրահատակի հղկում և լաքապատում", "Циклёвка и лакировка паркета", "Parquet sanding and varnishing", "صنفرة الباركيه وطلاؤه بالورنيش", "سنباده‌زنی و لاک‌زنی پارکت", "पार्केट की सैंडिंग और वार्निशिंग")),
        (new("ca435290-d3f1-5726-9968-45dc89a39c2a"), "renovation-flooring", "vinyl-flooring", WorkUnit.SquareMeter, WorkSurface.Floor, 1800, 2500, 3500, Text("Վինիլային հատակի (SPC, LVT) տեղադրում", "Укладка виниловых полов (SPC, LVT)", "Vinyl (SPC, LVT) flooring", "أرضيات الفينيل (SPC، LVT)", "کفپوش وینیل (SPC، LVT)", "विनाइल (SPC, LVT) फ़्लोरिंग")),
        (new("25cc4a6c-ac3c-5a63-b426-57079059bae3"), "renovation-flooring", "skirting-installation", WorkUnit.RunningMeter, WorkSurface.None, 600, 1000, 1500, Text("Պլինտուսի տեղադրում", "Монтаж плинтуса", "Skirting board installation", "تركيب النعلات (الوزرات)", "نصب قرنیز", "स्कर्टिंग बोर्ड लगाना")),
        (new("f8d31f97-6830-5eb1-987e-6ef5d8ea0520"), "renovation-flooring", "floor-covering-removal", WorkUnit.SquareMeter, WorkSurface.Floor, 800, 1500, 2500, Text("Հին հատակածածկի ապամոնտաժում", "Демонтаж старого напольного покрытия", "Old floor covering removal", "إزالة غطاء الأرضية القديم", "برداشتن کفپوش قدیمی", "पुरानी फ़्लोरिंग हटाना")),
        // renovation-screed
        (new("45c54bec-1bdd-5fd6-a8aa-446905eac9df"), "renovation-screed", "floor-screed", WorkUnit.SquareMeter, WorkSurface.Floor, 2000, 2500, 4000, Text("Հատակի լցահարթեցում (ստյաժկա)", "Стяжка пола", "Floor screed", "صبة تسوية الأرضية", "کف‌سازی با ملات (اسکرید)", "फ़र्श की स्क्रीडिंग")),
        (new("ba552c91-9d95-5acb-a9cf-e6c0e623b156"), "renovation-screed", "self-levelling-floor", WorkUnit.SquareMeter, WorkSurface.Floor, 1200, 1800, 2800, Text("Ինքնահարթեցվող հատակ", "Наливной пол", "Self-levelling floor", "أرضية ذاتية التسوية", "کف خودتراز", "सेल्फ़-लेवलिंग फ़्लोर")),
        // renovation-ceilings
        (new("c54b857f-a147-50cc-803e-ca5ae2ba71f7"), "renovation-ceilings", "stretch-ceiling", WorkUnit.SquareMeter, WorkSurface.Ceiling, 2000, 3000, 4500, Text("Ձգվող առաստաղի տեղադրում", "Монтаж натяжного потолка", "Stretch ceiling installation", "تركيب سقف مشدود", "نصب سقف کشسان", "स्ट्रेच सीलिंग लगाना")),
        (new("b6ee2a3f-4f15-5f62-9bf5-5154e21d5461"), "renovation-ceilings", "drywall-ceiling", WorkUnit.SquareMeter, WorkSurface.Ceiling, 4000, 5500, 8000, Text("Գիպսաստվարաթղթե առաստաղ", "Потолок из гипсокартона", "Drywall ceiling", "سقف من الجبس بورد", "سقف کاذب کناف", "जिप्सम बोर्ड फ़ॉल्स सीलिंग")),
        (new("87736dc2-df27-5bcf-a634-d6baf3d87105"), "renovation-ceilings", "multilevel-ceiling", WorkUnit.SquareMeter, WorkSurface.Ceiling, 6000, 8500, 12000, Text("Բազմամակարդակ գիպսաստվարաթղթե առաստաղ", "Многоуровневый потолок из гипсокартона", "Multi-level drywall ceiling", "سقف جبس بورد متعدد المستويات", "سقف کاذب کناف چندسطحی", "मल्टी-लेवल जिप्सम फ़ॉल्स सीलिंग")),
        (new("f105cf7f-81bf-5f92-87c6-16d0e76bb84b"), "renovation-ceilings", "ceiling-cornice", WorkUnit.RunningMeter, WorkSurface.None, 800, 1200, 2000, Text("Առաստաղի քիվի տեղադրում", "Монтаж потолочного плинтуса", "Ceiling cornice installation", "تركيب كرانيش السقف", "نصب ابزار گچی سقف", "सीलिंग कॉर्निस लगाना")),
        // renovation-drywall
        (new("93665c3c-046c-53bc-aaf8-6b08b4168da4"), "renovation-drywall", "drywall-partition", WorkUnit.SquareMeter, WorkSurface.Wall, 4000, 5000, 7500, Text("Գիպսաստվարաթղթե միջնապատ", "Перегородка из гипсокартона", "Drywall partition", "حائط فاصل من الجبس بورد", "دیوار جداکننده کناف", "जिप्सम बोर्ड पार्टिशन")),
        (new("727488ad-a41e-54ad-8e5d-db5d3611fe57"), "renovation-drywall", "drywall-wall-lining", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4000, 6000, Text("Պատերի երեսպատում գիպսաստվարաթղթով", "Обшивка стен гипсокартоном", "Drywall wall lining", "تكسية الجدران بالجبس بورد", "پوشش دیوار با کناف", "जिप्सम बोर्ड से दीवार की लाइनिंग")),
        (new("1d8b0bc5-7e17-52e7-a05b-2612d45ac434"), "renovation-drywall", "drywall-box-niche", WorkUnit.Piece, WorkSurface.None, 10000, 18000, 30000, Text("Գիպսաստվարաթղթե արկղ կամ խորշ", "Короб или ниша из гипсокартона", "Drywall box or niche", "صندوق أو تجويف من الجبس بورد", "باکس یا طاقچه کناف", "जिप्सम बोर्ड बॉक्स या आला")),
        // renovation-bathroom
        (new("9280b2ff-5817-52a9-829e-7f47794b34d7"), "renovation-bathroom", "bathroom-renovation", WorkUnit.Fixed, WorkSurface.None, 250000, 400000, 650000, Text("Լոգասենյակի ամբողջական վերանորոգում (մինչև 5 մ²)", "Ремонт ванной комнаты под ключ (до 5 м²)", "Full bathroom renovation (up to 5 m²)", "تجديد شامل للحمام (حتى 5 m²)", "بازسازی کامل حمام (تا 5 m²)", "पूरे बाथरूम का रेनोवेशन (5 m² तक)")),
        (new("538bde2c-6f8c-50be-bf5e-75378fc250f5"), "renovation-bathroom", "toilet-room-renovation", WorkUnit.Fixed, WorkSurface.None, 150000, 220000, 350000, Text("Զուգարանի վերանորոգում", "Ремонт туалета", "Toilet room renovation", "تجديد دورة المياه", "بازسازی سرویس بهداشتی", "टॉयलेट रूम का रेनोवेशन")),
        // renovation-kitchen
        (new("4b4e8317-3c82-5532-8a56-303bdff8d528"), "renovation-kitchen", "kitchen-renovation", WorkUnit.Fixed, WorkSurface.None, 300000, 500000, 800000, Text("Խոհանոցի ամբողջական վերանորոգում", "Ремонт кухни под ключ", "Full kitchen renovation", "تجديد شامل للمطبخ", "بازسازی کامل آشپزخانه", "पूरे किचन का रेनोवेशन")),
        (new("2bc1759e-5b47-5830-ba17-7e0554280a63"), "renovation-kitchen", "kitchen-backsplash", WorkUnit.SquareMeter, WorkSurface.Wall, 6000, 8000, 12000, Text("Խոհանոցի աշխատանքային պատի սալիկապատում", "Укладка кухонного фартука из плитки", "Kitchen backsplash tiling", "تبليط واجهة المطبخ الخلفية", "کاشی‌کاری بین کابینتی آشپزخانه", "किचन बैकस्प्लैश पर टाइल लगाना")),
        // renovation-decorative
        (new("3a79e4b4-32f4-522d-9926-c7ba3b80ebb0"), "renovation-decorative", "decorative-plaster", WorkUnit.SquareMeter, WorkSurface.Wall, 4000, 7000, 12000, Text("Դեկորատիվ սվաղ (վենետիկյան, ռելիեֆային)", "Декоративная штукатурка (венецианская, фактурная)", "Decorative plaster (Venetian, textured)", "لياسة ديكورية (فينيسية، محببة)", "اندود دکوراتیو (ونیزی، بافت‌دار)", "डेकोरेटिव प्लास्टर (वेनेशियन, टेक्सचर्ड)")),
        (new("4eaae419-375c-5c01-a1a7-67e382e7b16c"), "renovation-decorative", "microcement-finish", WorkUnit.SquareMeter, WorkSurface.Wall, 8000, 12000, 18000, Text("Միկրոցեմենտով հարդարում", "Отделка микроцементом", "Microcement finish", "تشطيب بالميكروسمنت", "پوشش میکروسمنت", "माइक्रोसीमेंट फ़िनिश")),
        (new("211c90e4-2429-539d-aaa2-3957233bc677"), "renovation-decorative", "decorative-wall-panels", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4500, 7000, Text("Դեկորատիվ պատի պանելներ", "Декоративные стеновые панели", "Decorative wall panels", "ألواح جدارية ديكورية", "دیوارپوش دکوراتیو", "डेकोरेटिव वॉल पैनल")),
        // plumbing-fixtures
        (new("ad56fcdb-622b-5b33-99d2-6271f077a337"), "plumbing-fixtures", "toilet-installation", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 22000, Text("Զուգարանակոնքի տեղադրում", "Установка унитаза", "Toilet installation", "تركيب المرحاض", "نصب توالت فرنگی", "कमोड (टॉयलेट सीट) लगाना")),
        (new("872591c5-9416-5f67-8adf-3dad920850fc"), "plumbing-fixtures", "wall-hung-toilet-installation", WorkUnit.Piece, WorkSurface.None, 20000, 30000, 45000, Text("Կախովի զուգարանակոնք ինստալյացիայով", "Подвесной унитаз с инсталляцией", "Wall-hung toilet with frame", "مرحاض معلق مع الإطار", "توالت وال‌هنگ همراه با فریم", "फ़्रेम के साथ वॉल-हंग टॉयलेट")),
        (new("39203f06-2d8e-5f8c-90ec-b2971bc44b3f"), "plumbing-fixtures", "sink-installation", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 18000, Text("Լվացարանի տեղադրում", "Установка раковины", "Sink installation", "تركيب المغسلة", "نصب روشویی", "वॉश बेसिन लगाना")),
        (new("b5d4bff0-cf90-5caf-b486-bed8db8ca0ce"), "plumbing-fixtures", "bathtub-installation", WorkUnit.Piece, WorkSurface.None, 15000, 22000, 35000, Text("Լոգարանի (վաննայի) տեղադրում", "Установка ванны", "Bathtub installation", "تركيب حوض الاستحمام", "نصب وان حمام", "बाथटब लगाना")),
        (new("cbbeac89-77e7-5bbe-a65e-9570c4a803e0"), "plumbing-fixtures", "shower-cabin-installation", WorkUnit.Piece, WorkSurface.None, 20000, 30000, 45000, Text("Ցնցուղախցիկի տեղադրում", "Установка душевой кабины", "Shower cabin installation", "تركيب كابينة الاستحمام", "نصب کابین دوش", "शॉवर केबिन लगाना")),
        (new("4bbb6d04-f423-5515-961e-24df9ed0c671"), "plumbing-fixtures", "walk-in-shower", WorkUnit.Piece, WorkSurface.None, 30000, 45000, 70000, Text("Ցնցուղ առանց խցիկի՝ հատակային տրապով", "Душ без поддона с трапом в полу", "Walk-in shower with floor drain", "دش مفتوح مع مصرف أرضي", "دوش بدون کابین با کفشور", "फ़्लोर ड्रेन के साथ वॉक-इन शॉवर")),
        (new("abe5e4ba-6cb8-57a6-9911-048b98b0d4a1"), "plumbing-fixtures", "faucet-installation", WorkUnit.Piece, WorkSurface.None, 4000, 6000, 9000, Text("Ծորակի տեղադրում", "Установка смесителя", "Faucet installation", "تركيب الحنفية", "نصب شیر آب", "नल लगाना")),
        (new("eb89ce3c-627a-5982-8ff8-ffd143942f72"), "plumbing-fixtures", "washing-machine-connection", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Լվացքի մեքենայի միացում", "Подключение стиральной машины", "Washing machine connection", "توصيل الغسالة", "اتصال ماشین لباسشویی", "वॉशिंग मशीन कनेक्शन")),
        (new("22dab37f-497e-5341-b6dd-051f5ce18459"), "plumbing-fixtures", "dishwasher-connection", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Աման լվացող մեքենայի միացում", "Подключение посудомоечной машины", "Dishwasher connection", "توصيل غسالة الصحون", "اتصال ماشین ظرفشویی", "डिशवॉशर कनेक्शन")),
        // plumbing-pipes
        (new("c0b8b7ae-7e4c-53cf-bd6b-4441c6d75b95"), "plumbing-pipes", "water-pipes-point", WorkUnit.Point, WorkSurface.None, 8000, 12000, 18000, Text("Ջրատար խողովակներ, 1 կետի համար", "Разводка водопровода, за точку", "Water pipes, per point", "تمديدات المياه، لكل نقطة", "لوله‌کشی آب، به ازای هر نقطه", "पानी की पाइपलाइन, प्रति पॉइंट")),
        (new("e3968fc2-0493-57fe-9f1b-07b57a0224bd"), "plumbing-pipes", "sewer-pipes-point", WorkUnit.Point, WorkSurface.None, 8000, 12000, 18000, Text("Կոյուղու խողովակներ, 1 կետի համար", "Разводка канализации, за точку", "Sewer pipes, per point", "تمديدات الصرف الصحي، لكل نقطة", "لوله‌کشی فاضلاب، به ازای هر نقطه", "सीवर पाइपलाइन, प्रति पॉइंट")),
        (new("a728f6f6-7267-5bef-90cc-2722bc6bb20e"), "plumbing-pipes", "water-riser-replacement", WorkUnit.Piece, WorkSurface.None, 20000, 30000, 50000, Text("Ջրի ստոյակի փոխարինում", "Замена стояка водоснабжения", "Water riser replacement", "استبدال خط المياه الرأسي", "تعویض رایزر آب", "पानी का राइज़र बदलना")),
        (new("5576975f-56a9-5364-8649-f838331c3c31"), "plumbing-pipes", "bathroom-plumbing", WorkUnit.Fixed, WorkSurface.None, 80000, 120000, 180000, Text("Լոգասենյակի սանտեխնիկական աշխատանքներ ամբողջությամբ", "Сантехнические работы в ванной под ключ", "Full bathroom plumbing", "تمديدات صحية شاملة للحمام", "لوله‌کشی کامل حمام", "पूरे बाथरूम की प्लंबिंग")),
        // plumbing-leaks
        (new("906cae97-6a91-57fe-925d-74b95b5d1fa6"), "plumbing-leaks", "leak-repair", WorkUnit.Fixed, WorkSurface.None, 8000, 15000, 25000, Text("Արտահոսքի հայտնաբերում և վերացում", "Поиск и устранение протечки", "Leak search and repair", "كشف التسربات وإصلاحها", "نشت‌یابی و تعمیر", "लीकेज ढूंढना और ठीक करना")),
        (new("1dcaa096-f354-5a11-83e9-11947fb82190"), "plumbing-leaks", "pipe-joint-repair", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Խողովակի միացման վերանորոգում", "Ремонт соединения труб", "Pipe joint repair", "إصلاح وصلات الأنابيب", "تعمیر اتصالات لوله", "पाइप जॉइंट की मरम्मत")),
        // plumbing-drain-cleaning
        (new("99f2bf00-dd94-5cb5-999f-903d32c2be9b"), "plumbing-drain-cleaning", "drain-unclogging", WorkUnit.Fixed, WorkSurface.None, 8000, 12000, 20000, Text("Խցանման վերացում", "Устранение засора", "Drain unclogging", "تسليك المجاري", "رفع گرفتگی لوله", "ड्रेन की ब्लॉकेज हटाना")),
        (new("8bc3ef52-e58e-56ab-9aca-85b00c9dff29"), "plumbing-drain-cleaning", "sewer-jetting", WorkUnit.RunningMeter, WorkSurface.None, 1500, 2500, 4000, Text("Կոյուղագծի մաքրում ջրի բարձր ճնշմամբ", "Гидродинамическая прочистка канализации", "Sewer line jetting", "تنظيف خط الصرف بضغط الماء", "شست‌وشوی لوله فاضلاب با فشار آب", "सीवर लाइन की जेटिंग")),
        // plumbing-water-heaters
        (new("57f2dfdd-4cc7-5df1-b20e-0e7b000e3456"), "plumbing-water-heaters", "water-heater-installation", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 22000, Text("Էլեկտրական ջրատաքացուցչի տեղադրում", "Установка электрического бойлера", "Electric water heater installation", "تركيب سخان مياه كهربائي", "نصب آبگرمکن برقی", "इलेक्ट्रिक गीज़र लगाना")),
        (new("1d04bcd5-fcfb-5eb3-9dfa-b1fabf8f5de2"), "plumbing-water-heaters", "instant-water-heater-installation", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 18000, Text("Հոսքային ջրատաքացուցչի տեղադրում", "Установка проточного водонагревателя", "Instant water heater installation", "تركيب سخان مياه فوري", "نصب آبگرمکن فوری", "इंस्टेंट गीज़र लगाना")),
        (new("e36c2eee-bfdb-5eb2-8470-3d0e46fbb3bc"), "plumbing-water-heaters", "water-heater-descaling", WorkUnit.Fixed, WorkSurface.None, 8000, 12000, 18000, Text("Ջրատաքացուցչի մաքրում նստվածքից", "Чистка бойлера от накипи", "Water heater descaling", "إزالة الترسبات الكلسية من سخان المياه", "رسوب‌زدایی آبگرمکن", "गीज़र की डीस्केलिंग")),
        // plumbing-pumps-filters
        (new("34593697-5dd9-5308-98f0-d5310cc11626"), "plumbing-pumps-filters", "water-pump-installation", WorkUnit.Piece, WorkSurface.None, 15000, 25000, 40000, Text("Ջրի պոմպի տեղադրում", "Установка водяного насоса", "Water pump installation", "تركيب مضخة مياه", "نصب پمپ آب", "वॉटर पंप लगाना")),
        (new("352cd5f1-1500-5c48-a500-3545fccc4753"), "plumbing-pumps-filters", "water-filter-installation", WorkUnit.Piece, WorkSurface.None, 6000, 10000, 15000, Text("Ջրի ֆիլտրի տեղադրում", "Установка фильтра для воды", "Water filter installation", "تركيب فلتر مياه", "نصب فیلتر تصفیه آب", "वॉटर फ़िल्टर लगाना")),
        (new("9ec73676-167a-5443-ade5-627a949839a6"), "plumbing-pumps-filters", "water-tank-installation", WorkUnit.Piece, WorkSurface.None, 15000, 25000, 40000, Text("Ջրի բաքի տեղադրում", "Установка накопительного бака для воды", "Water storage tank installation", "تركيب خزان مياه", "نصب مخزن آب", "पानी की टंकी लगाना")),
        // plumbing-meters
        (new("38df48cf-2034-5950-ba25-0aa45431b088"), "plumbing-meters", "water-meter-installation", WorkUnit.Piece, WorkSurface.None, 6000, 9000, 14000, Text("Ջրաչափի տեղադրում", "Установка счётчика воды", "Water meter installation", "تركيب عداد مياه", "نصب کنتور آب", "पानी का मीटर लगाना")),
        // heating-boilers
        (new("ed4cf38f-9aa6-5f5a-8a87-513d4cbecaa5"), "heating-boilers", "gas-boiler-installation", WorkUnit.Piece, WorkSurface.None, 30000, 45000, 70000, Text("Գազի կաթսայի տեղադրում", "Установка газового котла", "Gas boiler installation", "تركيب غلاية غاز", "نصب پکیج گازی", "गैस बॉयलर लगाना")),
        (new("136eae64-360b-5213-a91d-b906a4ec785f"), "heating-boilers", "gas-boiler-service", WorkUnit.Fixed, WorkSurface.None, 8000, 12000, 18000, Text("Գազի կաթսայի տարեկան սպասարկում", "Ежегодное обслуживание газового котла", "Gas boiler annual service", "الصيانة السنوية لغلاية الغاز", "سرویس سالانه پکیج گازی", "गैस बॉयलर की सालाना सर्विस")),
        (new("d4726908-97b9-5efc-ab52-a0125c757245"), "heating-boilers", "gas-boiler-repair", WorkUnit.Fixed, WorkSurface.None, 8000, 15000, 30000, Text("Գազի կաթսայի ախտորոշում և վերանորոգում", "Диагностика и ремонт газового котла", "Gas boiler diagnosis and repair", "تشخيص أعطال غلاية الغاز وإصلاحها", "عیب‌یابی و تعمیر پکیج گازی", "गैस बॉयलर की जांच और मरम्मत")),
        // heating-radiators
        (new("0d121576-10c4-5f17-8014-b94389cb556a"), "heating-radiators", "radiator-installation", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 22000, Text("Ռադիատորի տեղադրում", "Установка радиатора", "Radiator installation", "تركيب مشع تدفئة", "نصب رادیاتور", "रेडिएटर लगाना")),
        (new("5f6817d3-c7e6-5979-98d1-0b70438a3d43"), "heating-radiators", "radiator-replacement", WorkUnit.Piece, WorkSurface.None, 12000, 18000, 25000, Text("Ռադիատորի փոխարինում", "Замена радиатора", "Radiator replacement", "استبدال مشع تدفئة", "تعویض رادیاتور", "रेडिएटर बदलना")),
        (new("73d9b200-d878-53cb-bed4-ee8daba1eed5"), "heating-radiators", "towel-rail-installation", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 18000, Text("Սրբիչի տաքացուցչի տեղադրում", "Установка полотенцесушителя", "Heated towel rail installation", "تركيب سخان مناشف", "نصب حوله‌خشک‌کن", "हीटेड टॉवल रेल लगाना")),
        // heating-underfloor
        (new("d7ae22c4-80a4-5fcb-9d33-affe3abf043d"), "heating-underfloor", "water-underfloor-heating", WorkUnit.SquareMeter, WorkSurface.Floor, 3500, 5000, 7500, Text("Ջրային տաք հատակ", "Водяной тёплый пол", "Water underfloor heating", "تدفئة أرضية بالماء", "گرمایش از کف آبی", "पानी वाली अंडरफ़्लोर हीटिंग")),
        (new("40a4ea57-23cb-5d97-8be1-7c71dd82968e"), "heating-underfloor", "electric-underfloor-heating", WorkUnit.SquareMeter, WorkSurface.Floor, 2500, 3500, 5000, Text("Էլեկտրական տաք հատակ", "Электрический тёплый пол", "Electric underfloor heating", "تدفئة أرضية كهربائية", "گرمایش از کف برقی", "इलेक्ट्रिक अंडरफ़्लोर हीटिंग")),
        // heating-systems
        (new("afb50168-1605-510a-80a7-035056eddd45"), "heating-systems", "heating-system-installation", WorkUnit.SquareMeter, WorkSurface.Floor, 4000, 6000, 9000, Text("Ջեռուցման համակարգի տեղադրում, ջեռուցվող 1 մ²-ի համար", "Монтаж системы отопления, за м² отапливаемой площади", "Heating system installation, per m² heated", "تركيب نظام التدفئة، لكل m² مُدفأ", "نصب سیستم گرمایش، به ازای هر m² فضای گرمایشی", "हीटिंग सिस्टम लगाना, प्रति m² गर्म क्षेत्र")),
        (new("fc5c9b5d-8c58-5741-89b6-e705563e5f7f"), "heating-systems", "heating-system-flushing", WorkUnit.Fixed, WorkSurface.None, 20000, 35000, 60000, Text("Ջեռուցման համակարգի լվացում", "Промывка системы отопления", "Heating system flushing", "غسيل نظام التدفئة", "شست‌وشوی سیستم گرمایش", "हीटिंग सिस्टम की फ़्लशिंग")),
        // heating-gas-piping
        (new("c84742b2-7692-5b4a-b41c-5c585334d0af"), "heating-gas-piping", "indoor-gas-pipework", WorkUnit.RunningMeter, WorkSurface.None, 3000, 5000, 8000, Text("Ներքին գազատարի անցկացում", "Внутренняя разводка газа", "Indoor gas pipework", "تمديدات الغاز الداخلية", "لوله‌کشی گاز داخلی", "घर के अंदर गैस पाइपलाइन")),
        (new("e4e8c4a0-fb3d-596e-83bd-a1f67c3966c6"), "heating-gas-piping", "gas-stove-connection", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Գազօջախի միացում", "Подключение газовой плиты", "Gas stove connection", "توصيل موقد الغاز", "اتصال اجاق گاز", "गैस स्टोव कनेक्शन")),
        // heating-fireplaces
        (new("080808a0-8570-5be3-9974-57261f4d1a21"), "heating-fireplaces", "fireplace-installation", WorkUnit.Piece, WorkSurface.None, 80000, 150000, 300000, Text("Բուխարու տեղադրում", "Установка камина", "Fireplace installation", "تركيب مدفأة جدارية", "نصب شومینه", "फ़ायरप्लेस लगाना")),
        (new("ef57ae71-d978-57d8-93bf-3b6a10b4240d"), "heating-fireplaces", "chimney-installation", WorkUnit.RunningMeter, WorkSurface.None, 15000, 25000, 40000, Text("Ծխնելույզի տեղադրում", "Монтаж дымохода", "Chimney installation", "تركيب مدخنة", "نصب دودکش", "धुआं निकालने की चिमनी लगाना")),
        (new("aa1e03d5-636b-5fa4-af3f-cf53426183f1"), "heating-fireplaces", "wood-stove-installation", WorkUnit.Piece, WorkSurface.None, 30000, 50000, 80000, Text("Փայտի վառարանի տեղադրում", "Установка дровяной печи", "Wood stove installation", "تركيب مدفأة حطب", "نصب بخاری هیزمی", "लकड़ी वाला स्टोव लगाना")),
        // heating-heat-pumps
        (new("460e2f6b-543f-5879-9a17-fbf03f9f24af"), "heating-heat-pumps", "heat-pump-installation", WorkUnit.Piece, WorkSurface.None, 150000, 250000, 400000, Text("Ջերմային պոմպի տեղադրում", "Установка теплового насоса", "Heat pump installation", "تركيب مضخة حرارية", "نصب پمپ حرارتی", "हीट पंप लगाना")),
        (new("e1f587a2-528d-5e51-99a5-2c3bc8d030dd"), "heating-heat-pumps", "heat-pump-service", WorkUnit.Fixed, WorkSurface.None, 15000, 25000, 40000, Text("Ջերմային պոմպի սպասարկում", "Обслуживание теплового насоса", "Heat pump service", "صيانة المضخة الحرارية", "سرویس پمپ حرارتی", "हीट पंप सर्विस")),
        // electrical-wiring
        (new("6edea08a-7662-57a7-b7ce-3eeb85bca4db"), "electrical-wiring", "apartment-rewiring", WorkUnit.SquareMeter, WorkSurface.Floor, 3000, 4500, 7000, Text("Բնակարանի էլեկտրալարերի ամբողջական փոխարինում, 1 մ²-ի համար", "Полная замена электропроводки в квартире, за м²", "Full apartment rewiring, per m²", "إعادة تمديد الكهرباء للشقة بالكامل، لكل m²", "سیم‌کشی مجدد کامل آپارتمان، به ازای هر m²", "पूरे अपार्टमेंट की नई वायरिंग, प्रति m²")),
        (new("8c87ba96-1ef8-5e89-a9ad-067c8719be3d"), "electrical-wiring", "wall-chasing", WorkUnit.RunningMeter, WorkSurface.None, 800, 1200, 2000, Text("Պատերի ակոսում մալուխների համար", "Штробление стен под кабель", "Wall chasing for cables", "حفر مجاري الكابلات في الجدران", "شیارزنی دیوار برای کابل", "केबल के लिए दीवार में खांचा काटना")),
        (new("405f53e0-c392-51c2-9a57-34d010d70f3f"), "electrical-wiring", "cable-laying", WorkUnit.RunningMeter, WorkSurface.None, 300, 500, 900, Text("Մալուխի անցկացում", "Прокладка кабеля", "Cable laying", "تمديد الكابلات", "کابل‌کشی", "केबल बिछाना")),
        // electrical-sockets
        (new("9d3e65a0-4ae7-5f82-b027-8682905cff66"), "electrical-sockets", "socket-installation", WorkUnit.Point, WorkSurface.None, 2500, 3500, 5000, Text("Վարդակի տեղադրում", "Установка розетки", "Socket installation", "تركيب مقبس كهربائي", "نصب پریز", "सॉकेट लगाना")),
        (new("1c41857b-8d24-5279-9d09-8a600ab81998"), "electrical-sockets", "switch-installation", WorkUnit.Point, WorkSurface.None, 2000, 3000, 4500, Text("Անջատիչի տեղադրում", "Установка выключателя", "Switch installation", "تركيب مفتاح كهربائي", "نصب کلید برق", "स्विच लगाना")),
        (new("55b7e113-f820-5d4c-9464-4b4ca760ad92"), "electrical-sockets", "back-box-installation", WorkUnit.Point, WorkSurface.None, 1500, 2500, 4000, Text("Մոնտաժային տուփի տեղադրում բետոնում", "Установка подрозетника в бетон", "Back box installation in concrete", "تركيب علبة كهربائية في الخرسانة", "نصب قوطی برق در بتن", "कंक्रीट में बैक बॉक्स लगाना")),
        // electrical-lighting
        (new("83f122b5-0f61-5472-aafc-1cab03f2d4cd"), "electrical-lighting", "ceiling-light-installation", WorkUnit.Piece, WorkSurface.None, 4000, 6000, 10000, Text("Առաստաղի լուսատուի տեղադրում", "Установка потолочного светильника", "Ceiling light installation", "تركيب إنارة السقف", "نصب چراغ سقفی", "सीलिंग लाइट लगाना")),
        (new("37660565-e353-54dd-84b4-1b17662ca043"), "electrical-lighting", "chandelier-installation", WorkUnit.Piece, WorkSurface.None, 6000, 10000, 18000, Text("Ջահի տեղադրում", "Установка люстры", "Chandelier installation", "تركيب ثريا", "نصب لوستر", "झूमर लगाना")),
        (new("df07d90f-2ae3-5b2f-8154-daba46d0bc2d"), "electrical-lighting", "spotlight-installation", WorkUnit.Point, WorkSurface.None, 1500, 2500, 4000, Text("Կետային լուսատուի տեղադրում", "Установка точечного светильника", "Spotlight installation", "تركيب الإنارة الموجهة (سبوت لايت)", "نصب چراغ اسپات‌لایت", "स्पॉटलाइट लगाना")),
        (new("a3bbb17a-da4d-514f-9321-b047bf709c32"), "electrical-lighting", "led-strip-installation", WorkUnit.RunningMeter, WorkSurface.None, 1500, 2500, 4000, Text("LED ժապավենի տեղադրում", "Монтаж светодиодной ленты", "LED strip installation", "تركيب شريط LED", "نصب نوار LED", "LED स्ट्रिप लगाना")),
        // electrical-panels
        (new("83d79b3d-0b23-501f-8068-98fd995dbfe2"), "electrical-panels", "distribution-board-assembly", WorkUnit.Piece, WorkSurface.None, 25000, 40000, 70000, Text("Էլեկտրական վահանակի հավաքում", "Сборка электрощита", "Distribution board assembly", "تجميع لوحة التوزيع الكهربائية", "مونتاژ تابلو برق", "डिस्ट्रीब्यूशन बोर्ड असेंबली")),
        (new("17d5b708-f5e6-58bf-ac2e-31bcdafb4ac2"), "electrical-panels", "circuit-breaker-installation", WorkUnit.Piece, WorkSurface.None, 2500, 4000, 6000, Text("Ավտոմատ անջատիչի տեղադրում", "Установка автоматического выключателя", "Circuit breaker installation", "تركيب قاطع دائرة", "نصب کلید مینیاتوری (فیوز)", "सर्किट ब्रेकर (MCB) लगाना")),
        (new("b4bb7ab6-6d52-571e-9a57-f5635961d360"), "electrical-panels", "rcd-installation", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Պաշտպանական անջատման սարքի տեղադրում", "Установка УЗО", "Residual current device installation", "تركيب قاطع التيار المتبقي", "نصب کلید محافظ جان", "RCCB लगाना")),
        // electrical-repair
        (new("b7c31f92-4659-5a01-b877-ce07914a5328"), "electrical-repair", "electrical-fault-diagnosis", WorkUnit.Fixed, WorkSurface.None, 5000, 8000, 15000, Text("Էլեկտրական անսարքության ախտորոշում", "Диагностика неисправности электропроводки", "Electrical fault diagnosis", "تشخيص الأعطال الكهربائية", "عیب‌یابی برق", "बिजली की खराबी की जांच")),
        // electrical-solar
        (new("8fabb79a-adc9-5099-9b5c-d1a8bba8edeb"), "electrical-solar", "solar-panel-installation", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 20000, Text("Արևային վահանակի տեղադրում, 1 վահանակի համար", "Монтаж солнечной панели, за панель", "Solar panel installation, per panel", "تركيب الألواح الشمسية، لكل لوح", "نصب پنل خورشیدی، به ازای هر پنل", "सोलर पैनल लगाना, प्रति पैनल")),
        (new("82d0c6bb-7db0-53a2-902c-55143eff4fa7"), "electrical-solar", "solar-inverter-installation", WorkUnit.Piece, WorkSurface.None, 20000, 35000, 60000, Text("Արևային ինվերտորի տեղադրում", "Установка солнечного инвертора", "Solar inverter installation", "تركيب عاكس شمسي", "نصب اینورتر خورشیدی", "सोलर इन्वर्टर लगाना")),
        // electrical-generators
        (new("9eccfe56-0a6e-554d-8a41-aba698833471"), "electrical-generators", "generator-installation", WorkUnit.Piece, WorkSurface.None, 20000, 40000, 70000, Text("Գեներատորի տեղադրում", "Установка генератора", "Generator installation", "تركيب مولد كهربائي", "نصب ژنراتور", "जनरेटर लगाना")),
        (new("c7b89a66-75ca-5cb3-b90d-f45f3653e1ba"), "electrical-generators", "ups-installation", WorkUnit.Piece, WorkSurface.None, 8000, 15000, 25000, Text("Անխափան սնուցման սարքի (UPS) տեղադրում", "Установка ИБП", "UPS installation", "تركيب جهاز UPS", "نصب یو‌پی‌اس (UPS)", "UPS लगाना")),
        // electrical-ev-chargers
        (new("bf6245c1-bd8d-5caf-9182-1ffe3205b5b6"), "electrical-ev-chargers", "ev-charger-installation", WorkUnit.Piece, WorkSurface.None, 30000, 50000, 80000, Text("Էլեկտրամեքենայի լիցքավորման կայանի տեղադրում", "Установка зарядной станции для электромобиля", "Electric vehicle charger installation", "تركيب شاحن سيارة كهربائية", "نصب شارژر خودروی برقی", "इलेक्ट्रिक वाहन चार्जर लगाना")),
        // facade-stone
        (new("a67f356b-067a-53f5-b025-ec52dc6e436b"), "facade-stone", "facade-tuff-cladding", WorkUnit.SquareMeter, WorkSurface.Wall, 8000, 12000, 18000, Text("Ճակատի երեսպատում տուֆով", "Облицовка фасада туфом", "Facade cladding with tuff", "تكسية الواجهة بالتوف", "نماسازی با سنگ توف", "टफ़ पत्थर से फ़साड क्लैडिंग")),
        (new("06f5870c-d6ba-5b2b-b8a9-16e31563c57a"), "facade-stone", "facade-basalt-cladding", WorkUnit.SquareMeter, WorkSurface.Wall, 10000, 14000, 20000, Text("Ճակատի երեսպատում բազալտով", "Облицовка фасада базальтом", "Facade cladding with basalt", "تكسية الواجهة بالبازلت", "نماسازی با سنگ بازالت", "बेसाल्ट पत्थर से फ़साड क्लैडिंग")),
        // facade-plaster
        (new("0f9d891c-937d-5106-bbeb-1d449d36e70d"), "facade-plaster", "facade-plastering", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4500, 6500, Text("Ճակատի սվաղում", "Штукатурка фасада", "Facade plastering", "لياسة الواجهة", "اندود نما", "फ़साड पर प्लास्टर")),
        (new("27b55b4d-73f0-5d29-a786-fa607854bbad"), "facade-plaster", "facade-painting", WorkUnit.SquareMeter, WorkSurface.Wall, 1500, 2500, 4000, Text("Ճակատի ներկում", "Покраска фасада", "Facade painting", "دهان الواجهة", "رنگ‌آمیزی نما", "फ़साड पेंटिंग")),
        // facade-ventilated
        (new("9a130167-784a-5f4c-bc0f-b5deffa97ce1"), "facade-ventilated", "ventilated-facade-installation", WorkUnit.SquareMeter, WorkSurface.Wall, 6000, 9000, 14000, Text("Օդափոխվող ճակատի տեղադրում", "Монтаж вентилируемого фасада", "Ventilated facade installation", "تركيب واجهة مهواة", "اجرای نمای خشک (نمای تهویه‌دار)", "वेंटिलेटेड फ़साड लगाना")),
        // facade-composite
        (new("41e2d2e5-4e19-56be-adb6-d581c858ec82"), "facade-composite", "composite-panel-cladding", WorkUnit.SquareMeter, WorkSurface.Wall, 6000, 8000, 12000, Text("Կոմպոզիտային պանելներով երեսպատում", "Облицовка композитными панелями", "Composite panel cladding", "تكسية بألواح الكومبوزيت", "نماسازی با پنل کامپوزیت", "कम्पोज़िट पैनल (ACP) क्लैडिंग")),
        (new("46a94de4-80d9-508e-b2f9-a103c7214639"), "facade-composite", "siding-installation", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4500, 6500, Text("Սայդինգի տեղադրում", "Монтаж сайдинга", "Siding installation", "تركيب السايدنج", "نصب سایدینگ", "साइडिंग लगाना")),
        // facade-insulation
        (new("27489883-7c20-5f8d-ab6a-d31f9dd33bbf"), "facade-insulation", "facade-insulation-plaster", WorkUnit.SquareMeter, WorkSurface.Wall, 4000, 6000, 9000, Text("Ճակատի ջերմամեկուսացում սվաղային հարդարմամբ", "Утепление фасада с отделкой штукатуркой", "Facade insulation with plaster finish", "عزل الواجهة مع تشطيب باللياسة", "عایق‌کاری نما با پوشش اندود", "प्लास्टर फ़िनिश के साथ फ़साड इंसुलेशन")),
        // facade-restoration
        (new("92d75203-88b3-5296-a761-95ff99b57e34"), "facade-restoration", "facade-stone-restoration", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 5000, 8000, Text("Ճակատի քարի մաքրում և վերականգնում", "Очистка и реставрация камня фасада", "Facade stone cleaning and restoration", "تنظيف حجر الواجهة وترميمه", "شست‌وشو و مرمت سنگ نما", "फ़साड पत्थर की सफ़ाई और मरम्मत")),
        (new("5aff442b-49f6-57c8-8cf3-5fb097e3ff70"), "facade-restoration", "facade-joint-repair", WorkUnit.RunningMeter, WorkSurface.None, 1500, 2500, 4000, Text("Ճակատի կարերի վերանորոգում", "Ремонт швов фасада", "Facade joint repair", "إصلاح فواصل الواجهة", "ترمیم درزهای نما", "फ़साड जॉइंट की मरम्मत")),
        // facade-rope-access
        (new("c8eb3f2c-5388-5d26-8abb-5addf15588c4"), "facade-rope-access", "rope-access-work", WorkUnit.Hour, WorkSurface.None, 6000, 9000, 15000, Text("Արդյունաբերական ալպինիզմի աշխատանքներ", "Работы методом промышленного альпинизма", "Rope access work", "أعمال على الحبال في المرتفعات", "کار با طناب در ارتفاع", "रोप एक्सेस कार्य")),
        (new("d2aeed5d-66c9-5e1d-a4a1-668f4a17cb88"), "facade-rope-access", "panel-joint-sealing", WorkUnit.RunningMeter, WorkSurface.None, 1500, 2500, 4000, Text("Շենքի միջպանելային կարերի հերմետիկացում բարձրության վրա", "Герметизация межпанельных швов на высоте", "Sealing building panel joints at height", "عزل فواصل ألواح المبنى على ارتفاع", "درزگیری پانل‌های ساختمان در ارتفاع", "ऊंचाई पर बिल्डिंग पैनल जॉइंट की सीलिंग")),
        // cleaning-regular
        (new("c1601a3a-c55b-57e7-b10d-e7d00b098993"), "cleaning-regular", "regular-cleaning", WorkUnit.SquareMeter, WorkSurface.Floor, 150, 200, 300, Text("Պարբերական մաքրություն", "Регулярная уборка", "Regular cleaning", "تنظيف دوري", "نظافت دوره‌ای", "नियमित सफ़ाई")),
        (new("e69e6b5b-07a4-576c-a515-bb1bf871382d"), "cleaning-regular", "hourly-cleaning", WorkUnit.Hour, WorkSurface.None, 2000, 2500, 3500, Text("Ժամավճարով մաքրություն", "Почасовая уборка", "Cleaning by the hour", "تنظيف بالساعة", "نظافت ساعتی", "घंटे के हिसाब से सफ़ाई")),
        // cleaning-deep
        (new("fc6ba612-c8c2-5664-ae84-c7932935f067"), "cleaning-deep", "deep-cleaning", WorkUnit.SquareMeter, WorkSurface.Floor, 300, 450, 650, Text("Գլխավոր մաքրություն", "Генеральная уборка", "Deep cleaning", "تنظيف عميق", "نظافت عمیق", "डीप क्लीनिंग")),
        // cleaning-after-renovation
        (new("e13064fc-8f84-5d62-b3fb-b8697b5d97a4"), "cleaning-after-renovation", "post-renovation-cleaning", WorkUnit.SquareMeter, WorkSurface.Floor, 400, 600, 900, Text("Վերանորոգումից հետո մաքրություն", "Уборка после ремонта", "Cleaning after renovation", "تنظيف بعد التجديد", "نظافت پس از بازسازی", "रेनोवेशन के बाद सफ़ाई")),
        // cleaning-windows
        (new("3f76eb09-9219-53fc-ad97-db7cc0f10658"), "cleaning-windows", "window-cleaning", WorkUnit.SquareMeter, WorkSurface.None, 300, 500, 800, Text("Պատուհանների լվացում, ապակու 1 մ²-ի համար", "Мойка окон, за м² остекления", "Window cleaning, per m² of glass", "تنظيف النوافذ، لكل m² من الزجاج", "نظافت پنجره، به ازای هر m² شیشه", "खिड़की की सफ़ाई, प्रति m² कांच")),
        // cleaning-upholstery
        (new("20c4f17f-991e-5fc3-b517-12d1691f43f1"), "cleaning-upholstery", "sofa-cleaning", WorkUnit.Piece, WorkSurface.None, 3000, 4500, 7000, Text("Բազմոցի քիմմաքրում, 1 նստատեղի համար", "Химчистка дивана, за посадочное место", "Sofa cleaning, per seat", "تنظيف الكنب، لكل مقعد", "شست‌وشوی مبل، به ازای هر نفر", "सोफ़ा क्लीनिंग, प्रति सीट")),
        (new("28e82c72-b049-5964-b981-2cdb4523bba5"), "cleaning-upholstery", "mattress-cleaning", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Ներքնակի քիմմաքրում", "Химчистка матраса", "Mattress cleaning", "تنظيف المراتب", "شست‌وشوی تشک", "गद्दे की सफ़ाई")),
        (new("7964f874-2a67-53ca-bdcd-1a24613d744b"), "cleaning-upholstery", "chair-cleaning", WorkUnit.Piece, WorkSurface.None, 1000, 1500, 2500, Text("Փափուկ աթոռի քիմմաքրում", "Химчистка мягкого стула", "Upholstered chair cleaning", "تنظيف الكراسي المنجدة", "شست‌وشوی صندلی پارچه‌ای", "गद्दीदार कुर्सी की सफ़ाई")),
        // cleaning-carpets
        (new("6ff93d9c-f9ac-5203-a278-eae2c302bd84"), "cleaning-carpets", "carpet-cleaning", WorkUnit.SquareMeter, WorkSurface.None, 800, 1200, 1800, Text("Գորգերի լվացում", "Стирка ковров", "Carpet cleaning", "تنظيف السجاد", "قالیشویی", "कालीन की सफ़ाई")),
        (new("4610ab30-94aa-5fc9-89ab-8cec6b309d85"), "cleaning-carpets", "carpet-cleaning-at-home", WorkUnit.SquareMeter, WorkSurface.None, 1000, 1500, 2500, Text("Գորգերի մաքրում տանը", "Химчистка ковров на дому", "Carpet cleaning at home", "تنظيف السجاد في المنزل", "شست‌وشوی فرش در منزل", "घर पर कालीन की सफ़ाई")),
        // cleaning-offices
        (new("8fad2959-9bed-503a-929e-d04f0dfa97f2"), "cleaning-offices", "office-cleaning", WorkUnit.SquareMeter, WorkSurface.Floor, 150, 250, 400, Text("Գրասենյակի մաքրություն", "Уборка офиса", "Office cleaning", "تنظيف المكاتب", "نظافت دفتر کار", "ऑफ़िस की सफ़ाई")),
        // cleaning-move
        (new("f79559c3-2a18-5b9d-881a-7d880a3bdfa4"), "cleaning-move", "move-cleaning", WorkUnit.SquareMeter, WorkSurface.Floor, 300, 450, 700, Text("Մաքրություն տեղափոխվելուց առաջ կամ հետո", "Уборка при переезде", "Move-in or move-out cleaning", "تنظيف عند الانتقال إلى المسكن أو مغادرته", "نظافت هنگام اسباب‌کشی", "शिफ़्टिंग से पहले या बाद की सफ़ाई")),
        // cleaning-facades
        (new("4caea2b9-22d0-5635-923a-62798cc033f5"), "cleaning-facades", "glass-facade-cleaning", WorkUnit.SquareMeter, WorkSurface.Wall, 500, 800, 1300, Text("Ապակե ճակատի լվացում", "Мойка стеклянного фасада", "Glass facade cleaning", "تنظيف الواجهات الزجاجية", "نظافت نمای شیشه‌ای", "ग्लास फ़साड की सफ़ाई")),
        // cleaning-disinfection
        (new("8b227c04-0359-58f0-b57f-985c6317e7bb"), "cleaning-disinfection", "disinfection", WorkUnit.SquareMeter, WorkSurface.Floor, 150, 250, 400, Text("Ախտահանում", "Дезинфекция", "Disinfection", "تعقيم", "ضدعفونی", "डिसइन्फ़ेक्शन (कीटाणुशोधन)")),
        (new("3a3a8d87-1e83-5916-865a-997913144ca6"), "cleaning-disinfection", "pest-control", WorkUnit.Fixed, WorkSurface.None, 15000, 25000, 40000, Text("Բնակարանի միջատազերծում", "Дезинсекция квартиры", "Pest control treatment of an apartment", "مكافحة الحشرات في الشقة", "سم‌پاشی آپارتمان", "अपार्टमेंट में पेस्ट कंट्रोल")),
        // cleaning-kitchens
        (new("c14bea47-3356-5cb2-ab90-b4cbe84ff97d"), "cleaning-kitchens", "oven-cleaning", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Ջեռոցի մաքրում", "Чистка духовки", "Oven cleaning", "تنظيف الفرن", "تمیز کردن فر", "ओवन की सफ़ाई")),
        (new("5a24f466-11c3-56a1-b118-fac15dc5b998"), "cleaning-kitchens", "hood-cleaning", WorkUnit.Piece, WorkSurface.None, 5000, 7000, 10000, Text("Խոհանոցային օդաքաշի մաքրում", "Чистка кухонной вытяжки", "Kitchen hood cleaning", "تنظيف شفاط المطبخ", "تمیز کردن هود آشپزخانه", "किचन चिमनी की सफ़ाई")),
        (new("9cfe935d-d9f9-55d8-bc20-647b952ace74"), "cleaning-kitchens", "fridge-cleaning", WorkUnit.Piece, WorkSurface.None, 4000, 6000, 9000, Text("Սառնարանի մաքրում", "Мойка холодильника", "Fridge cleaning", "تنظيف الثلاجة", "تمیز کردن یخچال", "फ़्रिज की सफ़ाई")),
        // cleaning-yard
        (new("b0e2a76c-4e50-5d0d-b14b-b3e1487c75e7"), "cleaning-yard", "yard-cleaning", WorkUnit.SquareMeter, WorkSurface.None, 200, 350, 600, Text("Բակի մաքրում", "Уборка двора", "Yard cleaning", "تنظيف الفناء", "نظافت حیاط", "आंगन की सफ़ाई")),
        // roofing-new
        (new("c17b2078-6ed1-5e73-af9e-972d95465a83"), "roofing-new", "pitched-roof-installation", WorkUnit.SquareMeter, WorkSurface.None, 4000, 6000, 9000, Text("Թեք տանիքի տեղադրում", "Монтаж скатной кровли", "Pitched roof installation", "تنفيذ سقف مائل", "اجرای سقف شیب‌دار", "ढलवां छत का निर्माण")),
        (new("101154b0-ee46-532a-a35b-b2f61d48f2e5"), "roofing-new", "roof-truss-framing", WorkUnit.SquareMeter, WorkSurface.None, 3000, 4500, 7000, Text("Տանիքի հեծանային համակարգի տեղադրում", "Монтаж стропильной системы", "Roof truss framing", "تركيب هيكل جملونات السقف", "اجرای خرپای سقف", "छत के ट्रस फ़्रेम का निर्माण")),
        // roofing-repair
        (new("9b377e6f-ab80-54a7-ab84-6c689fb93c19"), "roofing-repair", "roof-repair", WorkUnit.SquareMeter, WorkSurface.None, 3000, 5000, 8000, Text("Տանիքի վերանորոգում", "Ремонт кровли", "Roof repair", "إصلاح السقف", "تعمیر بام", "छत की मरम्मत")),
        (new("79eda1f6-f154-5574-95db-90ea6eda28d5"), "roofing-repair", "roof-leak-repair", WorkUnit.Fixed, WorkSurface.None, 15000, 30000, 50000, Text("Տանիքի կաթոցի վերացում", "Устранение протечки кровли", "Roof leak repair", "إصلاح تسرب السقف", "رفع نشتی بام", "छत के लीकेज की मरम्मत")),
        // roofing-metal
        (new("d970e65a-433a-5617-9a38-dc161599d372"), "roofing-metal", "metal-tile-roofing", WorkUnit.SquareMeter, WorkSurface.None, 2500, 3500, 5000, Text("Մետաղական կղմինդրով տանիքածածկ", "Кровля из металлочерепицы", "Metal tile roofing", "تسقيف بالقرميد المعدني", "پوشش بام با شینگل فلزی", "मेटल टाइल रूफ़िंग")),
        (new("a8c194ac-5826-5389-9a87-050c6fd5cb8a"), "roofing-metal", "profiled-sheet-roofing", WorkUnit.SquareMeter, WorkSurface.None, 2000, 3000, 4500, Text("Պրոֆնաստիլով տանիքածածկ", "Кровля из профнастила", "Profiled sheet roofing", "تسقيف بالصاج المضلع", "پوشش بام با ورق ذوزنقه‌ای", "प्रोफ़ाइल शीट रूफ़िंग")),
        // roofing-flat
        (new("84e8e174-41c4-59a7-a0b4-3e4cd4dd65a5"), "roofing-flat", "flat-roof-membrane", WorkUnit.SquareMeter, WorkSurface.None, 2500, 3500, 5500, Text("Հարթ տանիքի ջրամեկուսացում մեմբրանով", "Мембранная гидроизоляция плоской кровли", "Flat roof membrane waterproofing", "عزل السطح المستوي بالأغشية", "عایق‌کاری بام تخت با ممبران", "सपाट छत की मेम्ब्रेन वॉटरप्रूफ़िंग")),
        (new("fade1600-d8b0-538d-9063-0ae9db772b8c"), "roofing-flat", "flat-roof-bitumen", WorkUnit.SquareMeter, WorkSurface.None, 2000, 3000, 4500, Text("Հարթ տանիքի ջրամեկուսացում բիտումով", "Битумная гидроизоляция плоской кровли", "Flat roof bitumen waterproofing", "عزل السطح المستوي بالبيتومين", "عایق‌کاری بام تخت با قیر", "सपाट छत की बिटुमेन वॉटरप्रूफ़िंग")),
        // roofing-gutters
        (new("9db61447-c6d5-5f7a-8646-02c7d2e546ad"), "roofing-gutters", "gutter-installation", WorkUnit.RunningMeter, WorkSurface.None, 1500, 2500, 4000, Text("Ջրհորդանի տեղադրում", "Монтаж водосточного желоба", "Gutter installation", "تركيب المزاريب", "نصب ناودان افقی", "रेन गटर लगाना")),
        (new("1711a2dd-9fcb-5db5-b3d5-8d753dc9748c"), "roofing-gutters", "downpipe-installation", WorkUnit.RunningMeter, WorkSurface.None, 1500, 2200, 3500, Text("Ջրահեռացման խողովակի տեղադրում", "Монтаж водосточной трубы", "Downpipe installation", "تركيب أنابيب تصريف مياه الأمطار", "نصب ناودان عمودی", "बारिश के पानी का डाउनपाइप लगाना")),
        (new("4ccfd4e4-8df7-586c-9052-083192594994"), "roofing-gutters", "gutter-cleaning", WorkUnit.RunningMeter, WorkSurface.None, 300, 500, 800, Text("Ջրհորդանների մաքրում", "Чистка водостоков", "Gutter cleaning", "تنظيف المزاريب", "تمیز کردن ناودان", "रेन गटर की सफ़ाई")),
        // roofing-attic
        (new("98af8d32-fdef-5da2-a67a-c2eee6d03a1e"), "roofing-attic", "attic-conversion-finishing", WorkUnit.SquareMeter, WorkSurface.Floor, 10000, 15000, 25000, Text("Ձեղնահարկի վերափոխում և հարդարում", "Отделка мансарды", "Attic conversion finishing", "تشطيب العلية لتحويلها إلى مساحة سكنية", "نازک‌کاری و تبدیل زیرشیروانی", "अटारी को रहने लायक बनाने की फ़िनिशिंग")),
        (new("6eab66e8-b49e-5347-b591-e65c89b0bddb"), "roofing-attic", "roof-window-installation", WorkUnit.Piece, WorkSurface.None, 25000, 40000, 60000, Text("Տանիքի պատուհանի տեղադրում", "Установка мансардного окна", "Roof window installation", "تركيب نافذة سقفية", "نصب پنجره سقفی", "छत की खिड़की (स्काईलाइट) लगाना")),
        // windows-pvc
        (new("a69cba31-f2ee-5fa0-ac79-653bea95851a"), "windows-pvc", "pvc-window-installation", WorkUnit.SquareMeter, WorkSurface.None, 4000, 6000, 9000, Text("Մետաղապլաստե պատուհանի տեղադրում, 1 մ²-ի համար", "Установка металлопластиковых окон, за м²", "uPVC window installation, per m²", "تركيب نوافذ uPVC، لكل m²", "نصب پنجره UPVC، به ازای هر m²", "uPVC खिड़की लगाना, प्रति m²")),
        (new("eb9017a9-ae49-5576-a4de-801a0b757ee5"), "windows-pvc", "window-sill-installation", WorkUnit.RunningMeter, WorkSurface.None, 2000, 3000, 5000, Text("Պատուհանագոգի տեղադրում", "Установка подоконника", "Window sill installation", "تركيب عتبة النافذة", "نصب سنگ زیر پنجره", "खिड़की की सिल लगाना")),
        (new("1a5aa403-6500-589e-b4b3-e5fab159eca1"), "windows-pvc", "window-reveal-finishing", WorkUnit.RunningMeter, WorkSurface.None, 3000, 4500, 7000, Text("Պատուհանի թեքությունների հարդարում", "Отделка оконных откосов", "Window reveal finishing", "تشطيب جوانب فتحة النافذة", "نازک‌کاری کناره‌های پنجره", "खिड़की के किनारों की फ़िनिशिंग")),
        // windows-aluminium
        (new("1abdc3ce-b058-5a1e-aee0-2fd342d95568"), "windows-aluminium", "aluminium-window-installation", WorkUnit.SquareMeter, WorkSurface.None, 5000, 7000, 10000, Text("Ալյումինե պատուհանի տեղադրում, 1 մ²-ի համար", "Установка алюминиевых окон, за м²", "Aluminium window installation, per m²", "تركيب نوافذ ألمنيوم، لكل m²", "نصب پنجره آلومینیومی، به ازای هر m²", "एल्युमिनियम खिड़की लगाना, प्रति m²")),
        (new("796dfebd-23c0-56e3-8465-683007773893"), "windows-aluminium", "glass-partition-installation", WorkUnit.SquareMeter, WorkSurface.None, 6000, 9000, 14000, Text("Ապակե միջնապատի տեղադրում", "Монтаж стеклянной перегородки", "Glass partition installation", "تركيب فاصل زجاجي", "نصب پارتیشن شیشه‌ای", "ग्लास पार्टिशन लगाना")),
        // windows-balcony
        (new("973929f0-4259-546e-b65a-9e1fbbcb2adc"), "windows-balcony", "balcony-glazing", WorkUnit.SquareMeter, WorkSurface.None, 5000, 7000, 10000, Text("Պատշգամբի ապակեպատում", "Остекление балкона", "Balcony glazing", "تزجيج الشرفة", "پوشش شیشه‌ای بالکن", "बालकनी में ग्लास लगाना")),
        // doors-interior
        (new("49c03afc-c04c-5fa8-9e9c-ca0085ebf675"), "doors-interior", "interior-door-installation", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 22000, Text("Միջսենյակային դռան տեղադրում", "Установка межкомнатной двери", "Interior door installation", "تركيب باب داخلي", "نصب درب داخلی", "अंदरूनी दरवाज़ा लगाना")),
        (new("0d4625a9-72a9-51ad-806b-79b63b8478c8"), "doors-interior", "sliding-door-installation", WorkUnit.Piece, WorkSurface.None, 15000, 22000, 35000, Text("Սահող դռան տեղադրում", "Установка раздвижной двери", "Sliding door installation", "تركيب باب منزلق", "نصب درب کشویی", "स्लाइडिंग दरवाज़ा लगाना")),
        // doors-entrance
        (new("8dbdb9e6-837a-51fa-9305-6ee38f83b226"), "doors-entrance", "entrance-door-installation", WorkUnit.Piece, WorkSurface.None, 15000, 22000, 35000, Text("Մուտքի դռան տեղադրում", "Установка входной двери", "Entrance door installation", "تركيب باب المدخل", "نصب درب ورودی", "मुख्य दरवाज़ा लगाना")),
        // windows-repair
        (new("923db82e-7f63-5977-8d7e-ee9008b450c9"), "windows-repair", "window-adjustment", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Պատուհանի կամ դռան կարգավորում", "Регулировка окон или дверей", "Window or door adjustment", "ضبط النوافذ أو الأبواب", "رگلاژ پنجره یا درب", "खिड़की या दरवाज़े का एडजस्टमेंट")),
        (new("6abfec99-f06b-5519-9984-93b26d1e8809"), "windows-repair", "window-seal-replacement", WorkUnit.RunningMeter, WorkSurface.None, 800, 1200, 2000, Text("Պատուհանի ռետինե միջադիրի փոխարինում", "Замена уплотнителя окна", "Window seal replacement", "استبدال جوان النافذة", "تعویض نوار درزگیر پنجره", "खिड़की की सील बदलना")),
        // windows-blinds
        (new("dcad5505-ef9a-5ff3-8406-cfac68bebbb2"), "windows-blinds", "blinds-installation", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Շերտավարագույրների տեղադրում", "Установка жалюзи", "Blinds installation", "تركيب الستائر (البلايند)", "نصب پرده کرکره‌ای", "ब्लाइंड्स लगाना")),
        (new("48a1b9f8-fe4d-5690-876e-9c18b2c74187"), "windows-blinds", "roller-shutter-installation", WorkUnit.SquareMeter, WorkSurface.None, 5000, 8000, 12000, Text("Ռոլետների տեղադրում", "Установка рольставней", "Roller shutter installation", "تركيب الشيش الدوار (الرول)", "نصب کرکره رول", "रोलर शटर लगाना")),
        // doors-garage
        (new("53fe59f3-8feb-5199-ba01-7684e86f1b56"), "doors-garage", "garage-door-installation", WorkUnit.Piece, WorkSurface.None, 50000, 80000, 130000, Text("Ավտոտնակի դարպասի տեղադրում", "Установка гаражных ворот", "Garage door installation", "تركيب باب المرآب", "نصب درب گاراژ", "गैराज का दरवाज़ा लगाना")),
        (new("814767ff-d202-532e-a13f-e2e0d6d6d888"), "doors-garage", "gate-automation-installation", WorkUnit.Piece, WorkSurface.None, 30000, 50000, 80000, Text("Դարպասի ավտոմատիկայի տեղադրում", "Установка автоматики для ворот", "Gate automation installation", "تركيب نظام فتح البوابة الآلي", "نصب سیستم بازکن خودکار درب حیاط", "गेट ऑटोमेशन लगाना")),
        // hvac-ac-installation
        (new("9e06a0b5-3fe8-5475-8301-6061cdc92484"), "hvac-ac-installation", "ac-installation-standard", WorkUnit.Piece, WorkSurface.None, 25000, 30000, 40000, Text("Սպլիտ օդորակիչի տեղադրում (մինչև 12 000 BTU)", "Установка сплит-системы (до 12 000 BTU)", "Split air conditioner installation (up to 12,000 BTU)", "تركيب مكيف سبليت (حتى 12,000 BTU)", "نصب کولر گازی اسپلیت (تا 12,000 BTU)", "स्प्लिट एसी लगाना (12,000 BTU तक)")),
        (new("f59e6c07-8429-58de-9cd5-6e7458f4c379"), "hvac-ac-installation", "ac-installation-large", WorkUnit.Piece, WorkSurface.None, 35000, 45000, 60000, Text("Սպլիտ օդորակիչի տեղադրում (18 000 BTU և ավելի)", "Установка сплит-системы (от 18 000 BTU)", "Split air conditioner installation (18,000 BTU and more)", "تركيب مكيف سبليت (18,000 BTU فأكثر)", "نصب کولر گازی اسپلیت (18,000 BTU و بیشتر)", "स्प्लिट एसी लगाना (18,000 BTU और ज़्यादा)")),
        (new("5055d29f-feda-5c61-8ade-4c9c97b14b6b"), "hvac-ac-installation", "ac-extra-pipe-route", WorkUnit.RunningMeter, WorkSurface.None, 4000, 6000, 9000, Text("Օդորակիչի լրացուցիչ խողովակաշար", "Дополнительная трасса кондиционера", "Extra air conditioner pipe route", "تمديد إضافي لأنابيب المكيف", "لوله‌کشی اضافه کولر گازی", "एसी की अतिरिक्त पाइपिंग")),
        (new("1d40dce5-d948-5a8a-9559-2ce51a4b5035"), "hvac-ac-installation", "ac-dismantling", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 18000, Text("Օդորակիչի ապամոնտաժում", "Демонтаж кондиционера", "Air conditioner dismantling", "فك المكيف", "باز کردن کولر گازی", "एसी उतारना (डिसमेंटलिंग)")),
        // hvac-ac-service
        (new("b45ba603-3098-5b62-bab2-6723327adfa7"), "hvac-ac-service", "ac-cleaning", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 18000, Text("Օդորակիչի մաքրում", "Чистка кондиционера", "Air conditioner cleaning", "تنظيف المكيف", "سرویس و شست‌وشوی کولر گازی", "एसी की सफ़ाई")),
        (new("addac716-d65d-531c-94b6-9cb7731a4c05"), "hvac-ac-service", "ac-refrigerant-refill", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 25000, Text("Օդորակիչի ֆրեոնի լիցքավորում", "Заправка кондиционера фреоном", "Air conditioner refrigerant refill", "تعبئة غاز التبريد للمكيف", "شارژ گاز کولر گازی", "एसी गैस रीफ़िलिंग")),
        // hvac-ventilation
        (new("eca1dff9-b194-5160-9651-38245ff00885"), "hvac-ventilation", "ventilation-duct-installation", WorkUnit.RunningMeter, WorkSurface.None, 3000, 5000, 8000, Text("Օդափոխության օդատարի տեղադրում", "Монтаж вентиляционного воздуховода", "Ventilation duct installation", "تركيب مجاري التهوية", "نصب کانال تهویه", "वेंटिलेशन डक्ट लगाना")),
        (new("1ff41a10-624b-55cb-b4f5-79d4cd32c1e7"), "hvac-ventilation", "exhaust-fan-installation", WorkUnit.Piece, WorkSurface.None, 4000, 6000, 10000, Text("Արտածծող օդափոխիչի տեղադրում", "Установка вытяжного вентилятора", "Exhaust fan installation", "تركيب مروحة شفط", "نصب هواکش", "एग्ज़ॉस्ट फ़ैन लगाना")),
        // hvac-hoods
        (new("f1da9962-b83d-5427-84e3-1bd52bdbfabc"), "hvac-hoods", "kitchen-hood-installation", WorkUnit.Piece, WorkSurface.None, 6000, 10000, 15000, Text("Խոհանոցային օդաքաշի տեղադրում", "Установка кухонной вытяжки", "Kitchen hood installation", "تركيب شفاط المطبخ", "نصب هود آشپزخانه", "किचन चिमनी लगाना")),
        // hvac-heat-recovery
        (new("ec9577d1-762f-56d3-9028-9804b3d27d88"), "hvac-heat-recovery", "heat-recovery-unit-installation", WorkUnit.Piece, WorkSurface.None, 25000, 40000, 70000, Text("Ռեկուպերացիայով օդափոխության սարքի տեղադրում", "Установка вентиляционной установки с рекуперацией", "Heat recovery ventilation unit installation", "تركيب وحدة تهوية مع استرجاع الحرارة", "نصب دستگاه تهویه با بازیافت حرارت", "हीट रिकवरी वेंटिलेशन यूनिट लगाना")),
        // insulation-thermal
        (new("d9c7dc35-9cfa-5dd9-94fe-3e37a8a6028e"), "insulation-thermal", "interior-wall-insulation", WorkUnit.SquareMeter, WorkSurface.Wall, 2500, 3500, 5500, Text("Պատերի ներքին ջերմամեկուսացում", "Утепление стен изнутри", "Interior wall insulation", "عزل الجدران من الداخل", "عایق‌کاری دیوار از داخل", "अंदरूनी दीवार का इंसुलेशन")),
        (new("c9fd15f2-52a2-56f3-9f7b-dffbefbc36da"), "insulation-thermal", "floor-insulation", WorkUnit.SquareMeter, WorkSurface.Floor, 1500, 2500, 4000, Text("Հատակի ջերմամեկուսացում", "Утепление пола", "Floor insulation", "عزل الأرضيات", "عایق‌کاری کف", "फ़र्श का इंसुलेशन")),
        // insulation-roof
        (new("811e2038-f7b2-5665-a244-b14bfb659009"), "insulation-roof", "roof-insulation", WorkUnit.SquareMeter, WorkSurface.Ceiling, 2000, 3000, 4500, Text("Տանիքի ջերմամեկուսացում", "Утепление кровли", "Roof insulation", "عزل السقف", "عایق‌کاری بام", "छत का इंसुलेशन")),
        // insulation-waterproofing
        (new("ff2a17f2-3198-52ae-a14b-4fa59b27e7af"), "insulation-waterproofing", "bathroom-waterproofing", WorkUnit.SquareMeter, WorkSurface.Floor, 1500, 2500, 4000, Text("Լոգասենյակի ջրամեկուսացում", "Гидроизоляция ванной комнаты", "Bathroom waterproofing", "عزل الحمام ضد الماء", "عایق‌کاری رطوبتی حمام", "बाथरूम वॉटरप्रूफ़िंग")),
        (new("9765e006-4645-5893-8f2b-6f6602a0f094"), "insulation-waterproofing", "basement-waterproofing", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 5000, 8000, Text("Նկուղի ջրամեկուսացում", "Гидроизоляция подвала", "Basement waterproofing", "عزل القبو ضد الماء", "عایق‌کاری رطوبتی زیرزمین", "बेसमेंट वॉटरप्रूफ़िंग")),
        (new("40f332de-01ef-596a-a64e-50f1d28d226b"), "insulation-waterproofing", "balcony-waterproofing", WorkUnit.SquareMeter, WorkSurface.Floor, 2500, 4000, 6000, Text("Պատշգամբի ջրամեկուսացում", "Гидроизоляция балкона", "Balcony waterproofing", "عزل الشرفة ضد الماء", "عایق‌کاری رطوبتی بالکن", "बालकनी वॉटरप्रूफ़िंग")),
        // insulation-sound
        (new("df929533-1208-5115-8bab-7b6968bb3896"), "insulation-sound", "wall-soundproofing", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4500, 7000, Text("Պատերի ձայնամեկուսացում", "Шумоизоляция стен", "Wall soundproofing", "عزل الجدران صوتياً", "عایق‌کاری صوتی دیوار", "दीवार की साउंडप्रूफ़िंग")),
        (new("9e9c873c-4a19-503a-a41b-5127aea6be00"), "insulation-sound", "ceiling-soundproofing", WorkUnit.SquareMeter, WorkSurface.Ceiling, 3500, 5000, 8000, Text("Առաստաղի ձայնամեկուսացում", "Шумоизоляция потолка", "Ceiling soundproofing", "عزل الأسقف صوتياً", "عایق‌کاری صوتی سقف", "छत की साउंडप्रूफ़िंग")),
        // insulation-spray-foam
        (new("4eb3cc9d-9ac5-5d4c-86a9-21cb094e5f25"), "insulation-spray-foam", "spray-foam-insulation", WorkUnit.SquareMeter, WorkSurface.Wall, 3000, 4500, 7000, Text("Փրփուրի փոշեցմամբ ջերմամեկուսացում", "Утепление напылением ППУ", "Spray foam insulation", "عزل بالرغوة المرشوشة", "عایق‌کاری با فوم پاششی", "स्प्रे फ़ोम इंसुलेशन")),
        // metalwork-railings
        (new("6ad4b5e1-73cb-5085-8b0d-2309d06fe1d9"), "metalwork-railings", "stair-railing", WorkUnit.RunningMeter, WorkSurface.None, 10000, 18000, 30000, Text("Աստիճանի բազրիքի պատրաստում և տեղադրում", "Изготовление и монтаж лестничных перил", "Stair railing fabrication and installation", "تصنيع درابزين الدرج وتركيبه", "ساخت و نصب نرده پله", "सीढ़ी की रेलिंग बनाना और लगाना")),
        (new("9a084f55-0b41-59b4-b1b2-1b0d8d809013"), "metalwork-railings", "balcony-railing", WorkUnit.RunningMeter, WorkSurface.None, 12000, 20000, 35000, Text("Պատշգամբի բազրիքի պատրաստում և տեղադրում", "Изготовление и монтаж балконного ограждения", "Balcony railing fabrication and installation", "تصنيع درابزين الشرفة وتركيبه", "ساخت و نصب نرده بالکن", "बालकनी की रेलिंग बनाना और लगाना")),
        // metalwork-gates-fences
        (new("b15a7d44-fbd7-57d7-b92d-34671ead796a"), "metalwork-gates-fences", "metal-fence-installation", WorkUnit.RunningMeter, WorkSurface.None, 6000, 10000, 16000, Text("Մետաղական ցանկապատի տեղադրում", "Установка металлического забора", "Metal fence installation", "تركيب سياج معدني", "نصب حصار فلزی", "मेटल फ़ेंसिंग लगाना")),
        (new("ae40705a-a136-51ae-8629-224bba7ab86d"), "metalwork-gates-fences", "metal-gate-fabrication", WorkUnit.Piece, WorkSurface.None, 60000, 100000, 180000, Text("Մետաղական դարպասի պատրաստում և տեղադրում", "Изготовление и установка металлических ворот", "Metal gate fabrication and installation", "تصنيع بوابة معدنية وتركيبها", "ساخت و نصب درب فلزی", "लोहे का गेट बनाना और लगाना")),
        // metalwork-structures
        (new("8d3c63ff-f3bc-58b6-94ef-383631a335b2"), "metalwork-structures", "steel-frame-structure", WorkUnit.SquareMeter, WorkSurface.Floor, 8000, 12000, 20000, Text("Պողպատե կարկասային կոնստրուկցիա, 1 մ²-ի համար", "Металлокаркас, за м²", "Steel frame structure, per m²", "هيكل فولاذي، لكل m²", "سازه اسکلت فلزی، به ازای هر m²", "स्टील फ़्रेम स्ट्रक्चर, प्रति m²")),
        (new("7f16127a-e2a6-525c-9987-acca0ccf2417"), "metalwork-structures", "steel-beam-installation", WorkUnit.RunningMeter, WorkSurface.None, 5000, 8000, 12000, Text("Պողպատե հեծանի տեղադրում", "Монтаж стальной балки", "Steel beam installation", "تركيب جسور فولاذية", "نصب تیرآهن", "स्टील बीम लगाना")),
        // metalwork-canopies
        (new("24717f94-392e-5821-8b79-258e27136efc"), "metalwork-canopies", "canopy-installation", WorkUnit.SquareMeter, WorkSurface.None, 6000, 9000, 14000, Text("Ծածկի կամ ավտոծածկի տեղադրում", "Монтаж навеса или автонавеса", "Canopy or carport installation", "تركيب مظلة أو مظلة سيارات", "نصب سایبان یا سایبان خودرو", "कैनोपी या कार शेड लगाना")),
        // metalwork-welding
        (new("cad2e150-242d-500a-b332-f0ca934225bd"), "metalwork-welding", "welding-work", WorkUnit.Hour, WorkSurface.None, 4000, 6000, 9000, Text("Եռակցման աշխատանքներ", "Сварочные работы", "Welding work", "أعمال اللحام", "جوشکاری", "वेल्डिंग का काम")),
        // metalwork-forging
        (new("5fa4e6bb-83e7-5832-b2b7-0d7135d445aa"), "metalwork-forging", "forged-railing", WorkUnit.RunningMeter, WorkSurface.None, 20000, 35000, 60000, Text("Դարբնոցային բազրիք", "Кованые перила", "Forged railing", "درابزين من الحديد المشغول", "نرده فرفورژه", "फ़ोर्ज्ड (रॉट आयरन) रेलिंग")),
        // metalwork-window-grilles
        (new("e33b3920-a5d5-5a34-8f64-96e3589a744b"), "metalwork-window-grilles", "window-grille-installation", WorkUnit.SquareMeter, WorkSurface.None, 8000, 12000, 18000, Text("Պատուհանի ճաղավանդակի պատրաստում և տեղադրում", "Изготовление и установка решёток на окна", "Window grille fabrication and installation", "تصنيع حماية النوافذ وتركيبها", "ساخت و نصب حفاظ پنجره", "खिड़की की ग्रिल बनाना और लगाना")),
        // carpentry-kitchens
        (new("00fd549e-d4a6-53d4-8578-43f13a9abc7d"), "carpentry-kitchens", "kitchen-cabinet-installation", WorkUnit.RunningMeter, WorkSurface.None, 8000, 12000, 18000, Text("Խոհանոցային կահույքի տեղադրում", "Установка кухонного гарнитура", "Kitchen cabinet installation", "تركيب خزائن المطبخ", "نصب کابینت آشپزخانه", "किचन कैबिनेट लगाना")),
        // carpentry-wardrobes
        (new("a53f4d7a-8f86-5d51-b468-ee38abdcc543"), "carpentry-wardrobes", "built-in-wardrobe-installation", WorkUnit.RunningMeter, WorkSurface.None, 6000, 10000, 15000, Text("Ներկառուցված զգեստապահարանի տեղադրում", "Установка встроенного шкафа", "Built-in wardrobe installation", "تركيب خزانة ملابس مدمجة", "نصب کمد دیواری", "बिल्ट-इन वार्डरोब लगाना")),
        // carpentry-assembly
        (new("2718331d-d1f0-5e9d-8cb6-560578789329"), "carpentry-assembly", "furniture-assembly", WorkUnit.Hour, WorkSurface.None, 3000, 4000, 6000, Text("Կահույքի հավաքում", "Сборка мебели", "Furniture assembly", "تجميع الأثاث", "مونتاژ مبلمان", "फ़र्नीचर असेंबली")),
        (new("8fc11747-990b-5479-8170-cfb4e0ae33b6"), "carpentry-assembly", "bed-assembly", WorkUnit.Piece, WorkSurface.None, 6000, 9000, 14000, Text("Մահճակալի հավաքում", "Сборка кровати", "Bed assembly", "تجميع السرير", "مونتاژ تخت خواب", "बेड असेंबली")),
        (new("0f812352-8502-5a80-9b8a-942e22b5ff40"), "carpentry-assembly", "wardrobe-assembly", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 20000, Text("Զգեստապահարանի հավաքում", "Сборка шкафа", "Wardrobe assembly", "تجميع خزانة الملابس", "مونتاژ کمد لباس", "अलमारी असेंबली")),
        // carpentry-furniture-repair
        (new("7bae6077-691f-5b81-ad96-12a06e45347a"), "carpentry-furniture-repair", "furniture-repair", WorkUnit.Hour, WorkSurface.None, 4000, 6000, 9000, Text("Կահույքի վերանորոգում", "Ремонт мебели", "Furniture repair", "إصلاح الأثاث", "تعمیر مبلمان", "फ़र्नीचर की मरम्मत")),
        (new("fe78cd39-a7e3-5da5-aee6-5cff4b397e33"), "carpentry-furniture-repair", "chair-reupholstery", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 20000, Text("Աթոռի վերապաստառում", "Перетяжка стула", "Chair reupholstery", "إعادة تنجيد الكراسي", "رویه‌کوبی مجدد صندلی", "कुर्सी की दोबारा अपहोल्स्ट्री")),
        (new("5c9a931f-2b3a-53dd-bb09-c1a0eab980ed"), "carpentry-furniture-repair", "sofa-reupholstery", WorkUnit.Piece, WorkSurface.None, 40000, 60000, 100000, Text("Բազմոցի վերապաստառում", "Перетяжка дивана", "Sofa reupholstery", "إعادة تنجيد الكنب", "رویه‌کوبی مجدد مبل", "सोफ़े की दोबारा अपहोल्स्ट्री")),
        // carpentry-wooden-stairs
        (new("7bc67481-cc45-5bf6-b63f-c1ae773f3605"), "carpentry-wooden-stairs", "wooden-step-cladding", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 25000, Text("Աստիճանի փայտե երեսպատում", "Облицовка ступени деревом", "Wooden cladding of a stair step", "تكسية درجة السلم بالخشب", "روکش چوبی پله", "सीढ़ी के स्टेप पर लकड़ी की क्लैडिंग")),
        (new("005b7ea3-01d7-5465-b951-1c10939fd0fe"), "carpentry-wooden-stairs", "wooden-staircase", WorkUnit.Piece, WorkSurface.None, 20000, 30000, 50000, Text("Փայտե աստիճանավանդակ, 1 աստիճանի համար", "Деревянная лестница, за ступень", "Wooden staircase, per step", "درج خشبي، لكل درجة", "پله چوبی، به ازای هر پله", "लकड़ी की सीढ़ी, प्रति स्टेप")),
        // carpentry-wooden-structures
        (new("0339b5bf-9adb-5065-82c8-6b0dbedd60ba"), "carpentry-wooden-structures", "wooden-deck", WorkUnit.SquareMeter, WorkSurface.Floor, 6000, 9000, 14000, Text("Փայտե տերասային հատակ", "Деревянный настил для террасы", "Wooden deck", "أرضية خشبية خارجية (ديك)", "دک چوبی", "लकड़ी का डेक")),
        (new("684da2f4-d8fd-5acd-8db5-5d6d17fa87c7"), "carpentry-wooden-structures", "gazebo-construction", WorkUnit.SquareMeter, WorkSurface.Floor, 15000, 25000, 40000, Text("Տաղավարի (բեսեդկայի) կառուցում", "Строительство беседки", "Gazebo construction", "بناء كشك حديقة", "ساخت آلاچیق", "गज़ेबो निर्माण")),
        // carpentry-countertops
        (new("235036de-7be6-562b-8712-f95cc397cbeb"), "carpentry-countertops", "countertop-installation", WorkUnit.RunningMeter, WorkSurface.None, 5000, 8000, 12000, Text("Սեղանի երեսի տեղադրում", "Установка столешницы", "Countertop installation", "تركيب سطح العمل", "نصب صفحه کابینت", "काउंटरटॉप लगाना")),
        (new("f6f05543-d5a9-5ba2-8b0a-f8186a40caec"), "carpentry-countertops", "countertop-cutout", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Սեղանի երեսին լվացարանի կամ սալօջախի համար անցքի բացում", "Вырез под мойку или варочную панель в столешнице", "Sink or hob cutout in a countertop", "قص فتحة للمغسلة أو الموقد في سطح العمل", "برش جای سینک یا گاز روی صفحه کابینت", "काउंटरटॉप में सिंक या हॉब के लिए कटआउट")),
        // earthworks-excavation
        (new("3157ff2e-9ac9-5aba-9c78-dcdef97692bf"), "earthworks-excavation", "manual-excavation", WorkUnit.CubicMeter, WorkSurface.None, 6000, 9000, 14000, Text("Հողի ձեռքով փորում", "Ручная выемка грунта", "Manual excavation", "حفر يدوي", "خاکبرداری دستی", "हाथ से खुदाई")),
        (new("3417820f-a5fd-55b9-bbec-11f56cad5e53"), "earthworks-excavation", "machine-excavation", WorkUnit.CubicMeter, WorkSurface.None, 1500, 2500, 4000, Text("Հողի մեքենայական փորում", "Механизированная выемка грунта", "Machine excavation", "حفر بالآليات", "خاکبرداری با ماشین‌آلات", "मशीन से खुदाई")),
        // earthworks-demolition
        (new("4259781c-fea0-550c-8575-16dc5bdb40b1"), "earthworks-demolition", "wall-demolition", WorkUnit.SquareMeter, WorkSurface.Wall, 2000, 3500, 6000, Text("Պատի քանդում", "Демонтаж стены", "Wall demolition", "هدم الجدران", "تخریب دیوار", "दीवार तोड़ना")),
        (new("e454c633-b0f0-581d-90a5-9c5ca882e8c8"), "earthworks-demolition", "concrete-demolition", WorkUnit.CubicMeter, WorkSurface.None, 15000, 25000, 40000, Text("Բետոնի քանդում", "Демонтаж бетона", "Concrete demolition", "هدم الخرسانة", "تخریب بتن", "कंक्रीट तोड़ना")),
        (new("dcd8fc75-66d0-5122-850c-1320e7fc9dc6"), "earthworks-demolition", "screed-demolition", WorkUnit.SquareMeter, WorkSurface.Floor, 1000, 1800, 3000, Text("Հատակի լցահարթեցման (ստյաժկայի) քանդում", "Демонтаж стяжки", "Screed demolition", "إزالة صبة التسوية", "تخریب کف‌سازی (اسکرید)", "स्क्रीड तोड़ना")),
        // earthworks-waste-removal
        (new("3c9414df-65bb-5166-b154-27e015ae3bf1"), "earthworks-waste-removal", "waste-removal-truck", WorkUnit.Fixed, WorkSurface.None, 15000, 25000, 40000, Text("Շինաղբի դուրսբերում, 1 մեքենայի համար", "Вывоз строительного мусора, за машину", "Construction waste removal, per truck", "نقل مخلفات البناء، لكل شاحنة", "حمل نخاله ساختمانی، به ازای هر کامیون", "निर्माण मलबा हटाना, प्रति ट्रक")),
        (new("c92bdb7a-3514-5f5f-982f-b8b5873c08d5"), "earthworks-waste-removal", "waste-bag-carrying", WorkUnit.Piece, WorkSurface.None, 200, 400, 700, Text("Աղբի պարկերի իջեցում, 1 պարկի համար", "Спуск мешков с мусором, за мешок", "Carrying waste bags down, per bag", "إنزال أكياس المخلفات، لكل كيس", "پایین آوردن کیسه نخاله، به ازای هر کیسه", "मलबे के बोरे नीचे उतारना, प्रति बोरा")),
        // earthworks-concrete-cutting
        (new("07cc3e8d-6416-5128-86cf-13307e6b3044"), "earthworks-concrete-cutting", "concrete-wall-cutting", WorkUnit.RunningMeter, WorkSurface.None, 8000, 12000, 20000, Text("Բետոնե պատի կտրում", "Резка бетонной стены", "Concrete wall cutting", "قص الجدران الخرسانية", "برش دیوار بتنی", "कंक्रीट की दीवार काटना")),
        (new("ba55b36c-9577-5b44-831a-5bcf7848ce9e"), "earthworks-concrete-cutting", "diamond-core-drilling", WorkUnit.Piece, WorkSurface.None, 3000, 6000, 10000, Text("Ալմաստե հորատում, 1 անցքի համար", "Алмазное сверление, за отверстие", "Diamond core drilling, per hole", "ثقب بالمثقاب الماسي، لكل ثقب", "کرگیری الماسه، به ازای هر سوراخ", "डायमंड कोर ड्रिलिंग, प्रति छेद")),
        // earthworks-equipment
        (new("91807c55-1f76-5192-807a-f4e4383147bb"), "earthworks-equipment", "excavator-rental", WorkUnit.Hour, WorkSurface.None, 12000, 15000, 20000, Text("Էքսկավատոր օպերատորով", "Экскаватор с оператором", "Excavator with operator", "حفارة مع مشغل", "بیل مکانیکی با اپراتور", "ऑपरेटर के साथ एक्सकेवेटर (JCB)")),
        (new("5b5705c1-05ff-503d-97ea-293605528227"), "earthworks-equipment", "crane-rental", WorkUnit.Hour, WorkSurface.None, 15000, 20000, 30000, Text("Կռունկ օպերատորով", "Кран с оператором", "Crane with operator", "رافعة مع مشغل", "جرثقیل با اپراتور", "ऑपरेटर के साथ क्रेन")),
        // earthworks-septic
        (new("2e39a77f-c4cd-562d-8960-31fe21cc9cfb"), "earthworks-septic", "septic-tank-installation", WorkUnit.Piece, WorkSurface.None, 80000, 150000, 250000, Text("Սեպտիկ հորի տեղադրում", "Установка септика", "Septic tank installation", "تركيب خزان صرف صحي (بيارة)", "نصب سپتیک تانک", "सेप्टिक टैंक लगाना")),
        (new("26aec2c1-435f-5cd4-a6ec-e90bce8de3c0"), "earthworks-septic", "drainage-installation", WorkUnit.RunningMeter, WorkSurface.None, 3000, 5000, 8000, Text("Դրենաժային համակարգի տեղադրում", "Монтаж дренажа", "Drainage installation", "تنفيذ نظام تصريف المياه", "اجرای سیستم زهکشی", "ड्रेनेज सिस्टम लगाना")),
        // earthworks-wells
        (new("4b2aca87-7685-5fad-bd5f-aaef153df685"), "earthworks-wells", "well-drilling", WorkUnit.RunningMeter, WorkSurface.None, 10000, 15000, 25000, Text("Հորատանցքի հորատում, խորության 1 մետրի համար", "Бурение скважины, за метр глубины", "Well drilling, per metre of depth", "حفر الآبار، لكل متر عمق", "حفر چاه، به ازای هر متر عمق", "बोरवेल खुदाई, प्रति मीटर गहराई")),
        // landscaping-design
        (new("ec9d7f4a-71b2-5ad0-89c4-ba0d615c9512"), "landscaping-design", "landscape-design", WorkUnit.SquareMeter, WorkSurface.None, 500, 1000, 2000, Text("Լանդշաֆտային դիզայն, տարածքի 1 մ²-ի համար", "Ландшафтный дизайн, за м² участка", "Landscape design, per m² of site", "تصميم المناظر الطبيعية، لكل m² من الموقع", "طراحی محوطه، به ازای هر m² زمین", "लैंडस्केप डिज़ाइन, प्रति m² साइट")),
        // landscaping-paving
        (new("29fba920-19e5-51fe-a88b-8e4718b058ea"), "landscaping-paving", "paving-installation", WorkUnit.SquareMeter, WorkSurface.None, 4000, 6000, 9000, Text("Սալահատակի տեղադրում", "Укладка тротуарной плитки", "Paving stone installation", "تركيب بلاط الأرصفة (الإنترلوك)", "سنگ‌فرش محوطه", "पेवर ब्लॉक लगाना")),
        (new("0612bbb1-213c-5305-b3ea-2b1322bace9d"), "landscaping-paving", "curb-installation", WorkUnit.RunningMeter, WorkSurface.None, 2000, 3000, 5000, Text("Եզրաքարի տեղադրում", "Установка бордюра", "Curb installation", "تركيب حجر الرصيف (البردورة)", "جدول‌گذاری", "कर्ब स्टोन लगाना")),
        // landscaping-lawns
        (new("6bcee1f9-f146-5cc8-ae3c-69e7f19b24e1"), "landscaping-lawns", "lawn-seeding", WorkUnit.SquareMeter, WorkSurface.None, 800, 1200, 2000, Text("Սիզամարգի ցանում", "Посев газона", "Lawn seeding", "زراعة بذور العشب", "کاشت بذر چمن", "लॉन के लिए घास के बीज बोना")),
        (new("fa20ad78-0bd5-5366-869e-ce68225f92e5"), "landscaping-lawns", "turf-laying", WorkUnit.SquareMeter, WorkSurface.None, 1000, 1500, 2500, Text("Գլանափաթեթային սիզամարգի փռում", "Укладка рулонного газона", "Turf laying", "فرش العشب الجاهز", "نصب چمن رولی", "रेडीमेड घास (टर्फ़) बिछाना")),
        (new("8d8b2c95-b388-5f84-8cc9-3bc26466a74f"), "landscaping-lawns", "tree-planting", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Ծառի կամ թփի տնկում", "Посадка деревьев или кустарников", "Tree or shrub planting", "زراعة الأشجار أو الشجيرات", "کاشت درخت یا درختچه", "पेड़ या झाड़ी लगाना")),
        (new("a3855644-7c03-5422-846a-188285d83360"), "landscaping-lawns", "lawn-mowing", WorkUnit.SquareMeter, WorkSurface.None, 50, 100, 150, Text("Սիզամարգի խուզում", "Стрижка газона", "Lawn mowing", "قص العشب", "چمن‌زنی", "लॉन की घास काटना")),
        // landscaping-irrigation
        (new("7849d0a6-0549-5224-9b3a-db456dd24349"), "landscaping-irrigation", "irrigation-system-installation", WorkUnit.SquareMeter, WorkSurface.None, 1500, 2500, 4000, Text("Ոռոգման համակարգի տեղադրում, տարածքի 1 մ²-ի համար", "Монтаж системы полива, за м² участка", "Irrigation system installation, per m² of site", "تركيب نظام الري، لكل m² من الموقع", "نصب سیستم آبیاری، به ازای هر m² زمین", "सिंचाई सिस्टम लगाना, प्रति m² साइट")),
        // landscaping-trees
        (new("6df44158-9c11-52dc-8ea0-8512dd444464"), "landscaping-trees", "tree-pruning", WorkUnit.Piece, WorkSurface.None, 5000, 10000, 20000, Text("Ծառերի էտում", "Обрезка деревьев", "Tree pruning", "تقليم الأشجار", "هرس درخت", "पेड़ों की छंटाई")),
        (new("c4d36796-9eef-55b4-a25c-01321465343b"), "landscaping-trees", "tree-removal", WorkUnit.Piece, WorkSurface.None, 15000, 30000, 60000, Text("Ծառի հատում", "Спил деревьев", "Tree removal", "إزالة الأشجار", "قطع و برداشتن درخت", "पेड़ हटाना")),
        // landscaping-pools
        (new("25e565be-3390-5511-8000-09c49e5a5a0c"), "landscaping-pools", "pool-construction", WorkUnit.SquareMeter, WorkSurface.None, 60000, 90000, 140000, Text("Լողավազանի կառուցում, լողավազանի 1 մ²-ի համար", "Строительство бассейна, за м² бассейна", "Swimming pool construction, per m² of pool", "بناء مسبح، لكل m² من المسبح", "ساخت استخر، به ازای هر m² استخر", "स्विमिंग पूल निर्माण, प्रति m² पूल")),
        (new("bf21ebcf-4e64-5883-b7e5-17778986159a"), "landscaping-pools", "pool-service", WorkUnit.Fixed, WorkSurface.None, 15000, 25000, 40000, Text("Լողավազանի սպասարկում", "Обслуживание бассейна", "Swimming pool service", "صيانة المسبح", "سرویس استخر", "स्विमिंग पूल सर्विस")),
        // landscaping-retaining-walls
        (new("c66c8540-e22c-5cd6-a7e7-4247c07d4af4"), "landscaping-retaining-walls", "retaining-wall-construction", WorkUnit.SquareMeter, WorkSurface.Wall, 8000, 12000, 18000, Text("Հենապատի կառուցում", "Строительство подпорной стены", "Retaining wall construction", "بناء جدار استنادي", "ساخت دیوار حائل", "रिटेनिंग वॉल निर्माण")),
        // security-cctv
        (new("f984bd06-2505-553e-8667-fa7156f1f730"), "security-cctv", "cctv-camera-installation", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 18000, Text("Տեսահսկման տեսախցիկի տեղադրում", "Установка камеры видеонаблюдения", "CCTV camera installation", "تركيب كاميرات المراقبة", "نصب دوربین مداربسته", "CCTV कैमरा लगाना")),
        (new("e43141bd-c1d3-5d81-a623-aa9e95058084"), "security-cctv", "video-recorder-setup", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 25000, Text("Տեսաձայնագրիչի տեղադրում և կարգավորում", "Установка и настройка видеорегистратора", "Video recorder installation and setup", "تركيب جهاز تسجيل الفيديو وضبطه", "نصب و راه‌اندازی دستگاه ضبط (DVR/NVR)", "वीडियो रिकॉर्डर (DVR/NVR) लगाना और सेटअप")),
        // security-alarms
        (new("c7a317af-b3db-5b0d-9317-52e62e394d97"), "security-alarms", "alarm-system-installation", WorkUnit.Fixed, WorkSurface.None, 30000, 50000, 80000, Text("Ազդանշանային համակարգի տեղադրում", "Монтаж охранной сигнализации", "Alarm system installation", "تركيب نظام إنذار", "نصب دزدگیر", "अलार्म सिस्टम लगाना")),
        (new("72eb416b-769d-5b34-976c-9a7bacaca38b"), "security-alarms", "alarm-sensor-installation", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Ազդանշանային տվիչի տեղադրում", "Установка датчика сигнализации", "Alarm sensor installation", "تركيب حساس إنذار", "نصب سنسور دزدگیر", "अलार्म सेंसर लगाना")),
        // security-intercoms
        (new("37de938d-9a9e-5628-acbb-04ff5bdeb051"), "security-intercoms", "intercom-installation", WorkUnit.Piece, WorkSurface.None, 10000, 15000, 25000, Text("Դոմոֆոնի տեղադրում", "Установка домофона", "Intercom installation", "تركيب جهاز الاتصال الداخلي (الإنتركم)", "نصب آیفون", "इंटरकॉम लगाना")),
        // security-access-control
        (new("fe4efe52-a0b7-525d-826e-5df750383d19"), "security-access-control", "access-control-installation", WorkUnit.Piece, WorkSurface.None, 20000, 35000, 60000, Text("Մուտքի վերահսկման համակարգի տեղադրում, 1 դռան համար", "Установка системы контроля доступа, за дверь", "Access control installation, per door", "تركيب نظام التحكم في الدخول، لكل باب", "نصب سیستم کنترل تردد، به ازای هر درب", "एक्सेस कंट्रोल लगाना, प्रति दरवाज़ा")),
        // security-smart-home
        (new("d23b912d-9d08-5894-be14-3aef9eebb7b3"), "security-smart-home", "smart-device-setup", WorkUnit.Piece, WorkSurface.None, 3000, 6000, 10000, Text("Խելացի սարքի տեղադրում և կարգավորում", "Установка и настройка умного устройства", "Smart device installation and setup", "تركيب الأجهزة الذكية وضبطها", "نصب و راه‌اندازی دستگاه هوشمند", "स्मार्ट डिवाइस लगाना और सेटअप")),
        (new("dce76d5c-4e3b-5150-bc4e-66d52c8dcc37"), "security-smart-home", "smart-home-system", WorkUnit.Fixed, WorkSurface.None, 50000, 100000, 200000, Text("Խելացի տան համակարգ բնակարանի համար", "Система «умный дом» для квартиры", "Smart home system for an apartment", "نظام المنزل الذكي لشقة", "سیستم خانه هوشمند برای آپارتمان", "अपार्टमेंट के लिए स्मार्ट होम सिस्टम")),
        // security-networks
        (new("6f3903df-0cae-5cb6-8b41-1a1ba82634af"), "security-networks", "network-point-installation", WorkUnit.Point, WorkSurface.None, 3000, 5000, 8000, Text("Ցանցային վարդակի տեղադրում", "Монтаж сетевой розетки", "Network point installation", "تركيب نقطة شبكة", "نصب پریز شبکه", "नेटवर्क पॉइंट लगाना")),
        (new("2f438e2a-cf7d-5f6d-9e8d-6f2c94494778"), "security-networks", "wifi-network-setup", WorkUnit.Fixed, WorkSurface.None, 5000, 10000, 20000, Text("Wi-Fi ցանցի կարգավորում", "Настройка сети Wi-Fi", "Wi-Fi network setup", "إعداد شبكة Wi-Fi", "راه‌اندازی شبکه وای‌فای", "Wi-Fi नेटवर्क सेटअप")),
        // security-fire-alarms
        (new("e8d533ab-5e82-57d4-8df6-6a949341c75f"), "security-fire-alarms", "smoke-detector-installation", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Ծխի տվիչի տեղադրում", "Установка датчика дыма", "Smoke detector installation", "تركيب كاشف دخان", "نصب دتکتور دود", "स्मोक डिटेक्टर लगाना")),
        // design-architecture
        (new("723cd598-b18f-58ab-b4ce-f947d4aed2b9"), "design-architecture", "architectural-design", WorkUnit.SquareMeter, WorkSurface.None, 2000, 4000, 8000, Text("Ճարտարապետական նախագծում, մակերեսի 1 մ²-ի համար", "Архитектурное проектирование, за м² площади", "Architectural design, per m² of floor area", "التصميم المعماري، لكل m² من المساحة", "طراحی معماری، به ازای هر m² زیربنا", "आर्किटेक्चरल डिज़ाइन, प्रति m² फ़्लोर एरिया")),
        // design-interior
        (new("54a76255-7f50-5f4d-b433-afe5dc47ec5c"), "design-interior", "interior-design", WorkUnit.SquareMeter, WorkSurface.None, 3000, 6000, 12000, Text("Ինտերիերի դիզայն, մակերեսի 1 մ²-ի համար", "Дизайн интерьера, за м² площади", "Interior design, per m² of floor area", "التصميم الداخلي، لكل m² من المساحة", "طراحی داخلی، به ازای هر m² زیربنا", "इंटीरियर डिज़ाइन, प्रति m² फ़्लोर एरिया")),
        (new("6164e6de-7b6f-5e2f-be17-5e09c44d779e"), "design-interior", "room-3d-visualization", WorkUnit.Piece, WorkSurface.None, 15000, 30000, 60000, Text("3D վիզուալիզացիա, 1 սենյակի համար", "3D-визуализация, за комнату", "3D visualization, per room", "تصور ثلاثي الأبعاد، لكل غرفة", "طراحی سه‌بعدی، به ازای هر اتاق", "3D विज़ुअलाइज़ेशन, प्रति कमरा")),
        // design-structural
        (new("745a0d35-14ab-554a-b853-a0662d95bc40"), "design-structural", "structural-design", WorkUnit.SquareMeter, WorkSurface.None, 1000, 2000, 4000, Text("Կոնստրուկտիվ նախագծում, մակերեսի 1 մ²-ի համար", "Конструктивное проектирование, за м² площади", "Structural design, per m² of floor area", "التصميم الإنشائي، لكل m² من المساحة", "طراحی سازه، به ازای هر m² زیربنا", "स्ट्रक्चरल डिज़ाइन, प्रति m² फ़्लोर एरिया")),
        // design-building-services
        (new("6b50be19-4ef5-5f55-87c3-f532aeca9edf"), "design-building-services", "building-services-design", WorkUnit.SquareMeter, WorkSurface.None, 1000, 2000, 3500, Text("Ինժեներական համակարգերի նախագծում, մակերեսի 1 մ²-ի համար", "Проектирование инженерных систем, за м² площади", "Building services design, per m² of floor area", "تصميم الأنظمة الكهروميكانيكية، لكل m² من المساحة", "طراحی تأسیسات ساختمان، به ازای هر m² زیربنا", "MEP डिज़ाइन, प्रति m² फ़्लोर एरिया")),
        // design-estimates
        (new("e15b8774-12b8-55b8-b77e-c68848ca7946"), "design-estimates", "cost-estimate", WorkUnit.Fixed, WorkSurface.None, 20000, 50000, 100000, Text("Նախագծի նախահաշվի կազմում", "Составление сметы проекта", "Cost estimate for a project", "تقدير تكلفة المشروع", "برآورد هزینه پروژه", "प्रोजेक्ट का लागत अनुमान")),
        // design-supervision
        (new("8a4fb2a6-3c88-5eec-bcb9-a459acc59201"), "design-supervision", "site-supervision-visit", WorkUnit.Piece, WorkSurface.None, 10000, 20000, 35000, Text("Տեխնիկական հսկողության այց օբյեկտ", "Выезд на объект для технадзора", "Site supervision visit", "زيارة إشراف على الموقع", "بازدید نظارت از کارگاه", "साइट सुपरविज़न विज़िट")),
        // design-surveys
        (new("248d1c1c-771e-5c89-a39b-197b88066642"), "design-surveys", "property-measurement", WorkUnit.Fixed, WorkSurface.None, 10000, 20000, 40000, Text("Գույքի չափագրում", "Обмер объекта", "Measuring a property", "قياس العقار", "اندازه‌گیری ملک", "प्रॉपर्टी की नाप-जोख")),
        (new("707ccc67-ce04-5936-a218-2a89e0d581f3"), "design-surveys", "topographic-survey", WorkUnit.Fixed, WorkSurface.None, 40000, 80000, 150000, Text("Հողամասի տեղագրական հանույթ", "Топографическая съёмка участка", "Topographic survey of a plot", "مسح طبوغرافي لقطعة أرض", "نقشه‌برداری توپوگرافی زمین", "प्लॉट का टोपोग्राफ़िक सर्वे")),
        // handyman-repairs
        (new("3ec5db97-56aa-51d8-8173-29bb6200ecb1"), "handyman-repairs", "handyman-hour", WorkUnit.Hour, WorkSurface.None, 3000, 4000, 6000, Text("Վարպետի աշխատանք", "Услуги мастера на час", "Handyman work", "أعمال الصيانة العامة", "کارهای فنی منزل", "हैंडीमैन का काम")),
        (new("a30d136f-e01a-567f-af4a-3bfedaa2f4fd"), "handyman-repairs", "handyman-call-out", WorkUnit.Fixed, WorkSurface.None, 5000, 7000, 10000, Text("Վարպետի կանչ՝ առաջին ժամը ներառյալ", "Вызов мастера с первым часом работы", "Handyman call-out with the first hour", "استدعاء عامل صيانة مع الساعة الأولى", "اعزام تعمیرکار با احتساب ساعت اول", "हैंडीमैन विज़िट, पहले घंटे सहित")),
        // handyman-mounting
        (new("22a2a903-ac64-513f-8045-f04a79533ab5"), "handyman-mounting", "tv-mounting", WorkUnit.Piece, WorkSurface.None, 8000, 12000, 18000, Text("Հեռուստացույցի ամրացում պատին", "Монтаж телевизора на стену", "TV wall mounting", "تثبيت التلفاز على الجدار", "نصب تلویزیون روی دیوار", "टीवी वॉल माउंटिंग")),
        (new("61f050a0-62cf-533e-a3be-5086e4445519"), "handyman-mounting", "shelf-mounting", WorkUnit.Piece, WorkSurface.None, 2000, 3500, 6000, Text("Դարակի ամրացում", "Навеска полки", "Shelf mounting", "تثبيت الرفوف", "نصب قفسه", "शेल्फ़ लगाना")),
        (new("08137ff8-9941-55ba-8a8b-128ce8741213"), "handyman-mounting", "curtain-rod-mounting", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Վարագույրաձողի ամրացում", "Монтаж карниза для штор", "Curtain rod mounting", "تثبيت قضيب الستائر", "نصب میله پرده", "पर्दे की रॉड लगाना")),
        (new("f024f08f-a094-54a0-8c2c-7443755c458c"), "handyman-mounting", "mirror-mounting", WorkUnit.Piece, WorkSurface.None, 3000, 5000, 8000, Text("Հայելու կամ նկարի ամրացում", "Навеска зеркала или картины", "Mirror or picture mounting", "تثبيت مرآة أو لوحة", "نصب آینه یا تابلو", "शीशा या तस्वीर लगाना")),
        // handyman-appliances
        (new("445006f6-246e-51b7-a92f-f20abd4dbc6b"), "handyman-appliances", "appliance-installation", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Կենցաղային տեխնիկայի տեղադրում", "Установка бытовой техники", "Household appliance installation", "تركيب الأجهزة المنزلية", "نصب لوازم خانگی", "घरेलू उपकरण लगाना")),
        (new("78151757-e548-5a57-8172-5278825f2b65"), "handyman-appliances", "hob-oven-connection", WorkUnit.Piece, WorkSurface.None, 6000, 10000, 15000, Text("Էլեկտրական սալօջախի կամ ջեռոցի միացում", "Подключение электрической варочной панели или духовки", "Electric hob or oven connection", "توصيل موقد أو فرن كهربائي", "اتصال اجاق برقی یا فر", "इलेक्ट्रिक हॉब या ओवन कनेक्शन")),
        // handyman-locks
        (new("959c2a65-0a58-5bb9-ad27-b23a243e0831"), "handyman-locks", "lock-replacement", WorkUnit.Piece, WorkSurface.None, 5000, 8000, 12000, Text("Կողպեքի փոխարինում", "Замена замка", "Lock replacement", "استبدال القفل", "تعویض قفل", "ताला बदलना")),
        (new("22edda47-2662-5043-b582-24fe6e455e8b"), "handyman-locks", "emergency-door-opening", WorkUnit.Fixed, WorkSurface.None, 10000, 15000, 25000, Text("Դռան վթարային բացում", "Аварийное вскрытие двери", "Emergency door opening", "فتح الأبواب في حالات الطوارئ", "بازکردن اضطراری درب", "आपातकालीन दरवाज़ा खोलना")),
        // handyman-sealing
        (new("de7bb175-4ece-5767-84bf-bbb921eba2ea"), "handyman-sealing", "silicone-sealing", WorkUnit.RunningMeter, WorkSurface.None, 800, 1200, 2000, Text("Սիլիկոնային հերմետիկացում", "Герметизация силиконом", "Silicone sealing", "العزل بالسيليكون", "درزگیری با سیلیکون", "सिलिकॉन सीलिंग")),
    ];
}
