<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\HomeServices.Api\HomeServices.Api.csproj" />
  </ItemGroup>
</Project>
