<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\HomeServices.Infrastructure\HomeServices.Infrastructure.csproj" />
  </ItemGroup>
</Project>
