// <auto-generated />
using System;
using HomeServices.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeServices.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003132836_AddLanguages")]
    partial class AddLanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeServices.Domain.Localization.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("native_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_is_default")
                        .HasFilter("is_default = true");

                    b.ToTable("languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000001"),
                            Code = "hy",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Armenian",
                            NativeName = "Հայերեն",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000002"),
                            Code = "ru",
                            IsActive = true,
                            IsDefault = false,
                            Name = "Russian",
                            NativeName = "Русский",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000003"),
                            Code = "en",
                            IsActive = true,
                            IsDefault = false,
                            Name = "English",
                            NativeName = "English",
                            SortOrder = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
