// <auto-generated />
using System;
using System.Collections.Generic;
using HomeServices.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeServices.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003144215_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeServices.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_log_actor_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_occurred_at");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("HomeServices.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Icon")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000101"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "brick",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "{\"hy\":\"\\u0547\\u056B\\u0576\\u0561\\u0580\\u0561\\u0580\\u0578\\u0582\\u0569\\u0575\\u0578\\u0582\\u0576\",\"ru\":\"\\u0421\\u0442\\u0440\\u043E\\u0438\\u0442\\u0435\\u043B\\u044C\\u0441\\u0442\\u0432\\u043E\",\"en\":\"Construction\"}",
                            Slug = "construction",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000102"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "roller",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "{\"hy\":\"\\u054E\\u0565\\u0580\\u0561\\u0576\\u0578\\u0580\\u0578\\u0563\\u0578\\u0582\\u0574\",\"ru\":\"\\u0420\\u0435\\u043C\\u043E\\u043D\\u0442\",\"en\":\"Renovation\"}",
                            Slug = "renovation",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000103"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "pipe",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "{\"hy\":\"\\u054D\\u0561\\u0576\\u057F\\u0565\\u056D\\u0576\\u056B\\u056F\\u0561\",\"ru\":\"\\u0421\\u0430\\u043D\\u0442\\u0435\\u0445\\u043D\\u0438\\u043A\\u0430\",\"en\":\"Plumbing\"}",
                            Slug = "plumbing",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000104"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "flame",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "{\"hy\":\"\\u054B\\u0565\\u057C\\u0578\\u0582\\u0581\\u0578\\u0582\\u0574\",\"ru\":\"\\u041E\\u0442\\u043E\\u043F\\u043B\\u0435\\u043D\\u0438\\u0435\",\"en\":\"Heating\"}",
                            Slug = "heating",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000105"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "bolt",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "{\"hy\":\"\\u0537\\u056C\\u0565\\u056F\\u057F\\u0580\\u0561\\u056F\\u0561\\u0576 \\u0561\\u0577\\u056D\\u0561\\u057F\\u0561\\u0576\\u0584\\u0576\\u0565\\u0580\",\"ru\":\"\\u042D\\u043B\\u0435\\u043A\\u0442\\u0440\\u043E\\u043C\\u043E\\u043D\\u0442\\u0430\\u0436\\u043D\\u044B\\u0435 \\u0440\\u0430\\u0431\\u043E\\u0442\\u044B\",\"en\":\"Electrical work\"}",
                            Slug = "electrical",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000106"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "facade",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "{\"hy\":\"\\u0556\\u0561\\u057D\\u0561\\u0564\\u056B \\u0565\\u0580\\u0565\\u057D\\u057A\\u0561\\u057F\\u0578\\u0582\\u0574\",\"ru\":\"\\u041E\\u0431\\u043B\\u0438\\u0446\\u043E\\u0432\\u043A\\u0430 \\u0444\\u0430\\u0441\\u0430\\u0434\\u0430\",\"en\":\"Exterior cladding\"}",
                            Slug = "exterior-cladding",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000107"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "sparkle",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "{\"hy\":\"\\u054A\\u0580\\u0578\\u0586\\u0565\\u057D\\u056B\\u0578\\u0576\\u0561\\u056C \\u0574\\u0561\\u0584\\u0580\\u0578\\u0582\\u0574\",\"ru\":\"\\u041F\\u0440\\u043E\\u0444\\u0435\\u0441\\u0441\\u0438\\u043E\\u043D\\u0430\\u043B\\u044C\\u043D\\u0430\\u044F \\u0443\\u0431\\u043E\\u0440\\u043A\\u0430\",\"en\":\"Professional cleaning\"}",
                            Slug = "cleaning",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("HomeServices.Domain.Catalog.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_slug");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0535\\u0580\\u0587\\u0561\\u0576\",\"ru\":\"\\u0415\\u0440\\u0435\\u0432\\u0430\\u043D\",\"en\":\"Yerevan\"}",
                            Slug = "yerevan",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000202"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0537\\u057B\\u0574\\u056B\\u0561\\u056E\\u056B\\u0576\",\"ru\":\"\\u042D\\u0447\\u043C\\u0438\\u0430\\u0434\\u0437\\u0438\\u043D\",\"en\":\"Ejmiatsin\"}",
                            Slug = "ejmiatsin",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000203"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0531\\u0562\\u0578\\u057E\\u0575\\u0561\\u0576\",\"ru\":\"\\u0410\\u0431\\u043E\\u0432\\u044F\\u043D\",\"en\":\"Abovyan\"}",
                            Slug = "abovyan",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000204"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0531\\u0577\\u057F\\u0561\\u0580\\u0561\\u056F\",\"ru\":\"\\u0410\\u0448\\u0442\\u0430\\u0440\\u0430\\u043A\",\"en\":\"Ashtarak\"}",
                            Slug = "ashtarak",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000205"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0544\\u0561\\u057D\\u056B\\u057D\",\"ru\":\"\\u041C\\u0430\\u0441\\u0438\\u0441\",\"en\":\"Masis\"}",
                            Slug = "masis",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("HomeServices.Domain.Catalog.District", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("CityId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_districts_city_id_slug");

                    b.ToTable("districts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000301"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0531\\u057B\\u0561\\u0583\\u0576\\u0575\\u0561\\u056F\",\"ru\":\"\\u0410\\u0447\\u0430\\u043F\\u043D\\u044F\\u043A\",\"en\":\"Ajapnyak\"}",
                            Slug = "ajapnyak",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000302"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0531\\u0580\\u0561\\u0562\\u056F\\u056B\\u0580\",\"ru\":\"\\u0410\\u0440\\u0430\\u0431\\u043A\\u0438\\u0440\",\"en\":\"Arabkir\"}",
                            Slug = "arabkir",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000303"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0531\\u057E\\u0561\\u0576\",\"ru\":\"\\u0410\\u0432\\u0430\\u043D\",\"en\":\"Avan\"}",
                            Slug = "avan",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000304"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0534\\u0561\\u057E\\u0569\\u0561\\u0577\\u0565\\u0576\",\"ru\":\"\\u0414\\u0430\\u0432\\u0442\\u0430\\u0448\\u0435\\u043D\",\"en\":\"Davtashen\"}",
                            Slug = "davtashen",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000305"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0537\\u0580\\u0565\\u0562\\u0578\\u0582\\u0576\\u056B\",\"ru\":\"\\u042D\\u0440\\u0435\\u0431\\u0443\\u043D\\u0438\",\"en\":\"Erebuni\"}",
                            Slug = "erebuni",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000306"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0554\\u0561\\u0576\\u0561\\u0584\\u0565\\u057C-\\u0536\\u0565\\u0575\\u0569\\u0578\\u0582\\u0576\",\"ru\":\"\\u041A\\u0430\\u043D\\u0430\\u043A\\u0435\\u0440-\\u0417\\u0435\\u0439\\u0442\\u0443\\u043D\",\"en\":\"Kanaker-Zeytun\"}",
                            Slug = "kanaker-zeytun",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000307"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u053F\\u0565\\u0576\\u057F\\u0580\\u0578\\u0576\",\"ru\":\"\\u041A\\u0435\\u043D\\u0442\\u0440\\u043E\\u043D\",\"en\":\"Kentron\"}",
                            Slug = "kentron",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000308"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0544\\u0561\\u056C\\u0561\\u0569\\u056B\\u0561-\\u054D\\u0565\\u0562\\u0561\\u057D\\u057F\\u056B\\u0561\",\"ru\":\"\\u041C\\u0430\\u043B\\u0430\\u0442\\u0438\\u044F-\\u0421\\u0435\\u0431\\u0430\\u0441\\u0442\\u0438\\u044F\",\"en\":\"Malatia-Sebastia\"}",
                            Slug = "malatia-sebastia",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000309"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0546\\u0578\\u0580 \\u0546\\u0578\\u0580\\u0584\",\"ru\":\"\\u041D\\u043E\\u0440 \\u041D\\u043E\\u0440\\u043A\",\"en\":\"Nor Nork\"}",
                            Slug = "nor-nork",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000310"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0546\\u0578\\u0580\\u0584-\\u0544\\u0561\\u0580\\u0561\\u0577\",\"ru\":\"\\u041D\\u043E\\u0440\\u043A-\\u041C\\u0430\\u0440\\u0430\\u0448\",\"en\":\"Nork-Marash\"}",
                            Slug = "nork-marash",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000311"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0546\\u0578\\u0582\\u0562\\u0561\\u0580\\u0561\\u0577\\u0565\\u0576\",\"ru\":\"\\u041D\\u0443\\u0431\\u0430\\u0440\\u0430\\u0448\\u0435\\u043D\",\"en\":\"Nubarashen\"}",
                            Slug = "nubarashen",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000312"),
                            CityId = new Guid("019a0000-0000-7000-8000-000000000201"),
                            IsActive = true,
                            Name = "{\"hy\":\"\\u0547\\u0565\\u0576\\u0563\\u0561\\u057E\\u056B\\u0569\",\"ru\":\"\\u0428\\u0435\\u043D\\u0433\\u0430\\u0432\\u0438\\u0442\",\"en\":\"Shengavit\"}",
                            Slug = "shengavit",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("HomeServices.Domain.Identity.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_otp_codes");

                    b.HasIndex("Phone", "CreatedAt")
                        .HasDatabaseName("ix_otp_codes_phone_created_at");

                    b.ToTable("otp_codes");
                });

            modelBuilder.Entity("HomeServices.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("HomeServices.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone");

                    b.Property<int>("Roles")
                        .HasColumnType("integer")
                        .HasColumnName("roles");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HomeServices.Domain.Localization.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("native_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_code");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_languages_is_default")
                        .HasFilter("is_default = true");

                    b.ToTable("languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000001"),
                            Code = "hy",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Armenian",
                            NativeName = "Հայերեն",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000002"),
                            Code = "ru",
                            IsActive = true,
                            IsDefault = false,
                            Name = "Russian",
                            NativeName = "Русский",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("019a0000-0000-7000-8000-000000000003"),
                            Code = "en",
                            IsActive = true,
                            IsDefault = false,
                            Name = "English",
                            NativeName = "English",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("HomeServices.Domain.Staff.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<string>>("_permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("HomeServices.Domain.Staff.StaffRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_user_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_staff_refresh_tokens");

                    b.HasIndex("StaffUserId")
                        .HasDatabaseName("ix_staff_refresh_tokens_staff_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_refresh_tokens_token_hash");

                    b.ToTable("staff_refresh_tokens");
                });

            modelBuilder.Entity("HomeServices.Domain.Staff.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedSignInCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_sign_in_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at");

                    b.Property<long?>("LastTotpTimeStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_totp_time_step");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PendingTotpSecret")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pending_totp_secret");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("totp_secret");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_staff_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_users_email");

                    b.ToTable("staff_users");
                });

            modelBuilder.Entity("HomeServices.Domain.Staff.StaffUserRole", b =>
                {
                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("StaffUserId", "RoleId")
                        .HasName("pk_staff_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_staff_user_role_role_id");

                    b.ToTable("staff_user_role");
                });

            modelBuilder.Entity("HomeServices.Domain.Catalog.Category", b =>
                {
                    b.HasOne("HomeServices.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");
                });

            modelBuilder.Entity("HomeServices.Domain.Catalog.District", b =>
                {
                    b.HasOne("HomeServices.Domain.Catalog.City", null)
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_districts_cities_city_id");
                });

            modelBuilder.Entity("HomeServices.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("HomeServices.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("HomeServices.Domain.Staff.StaffRefreshToken", b =>
                {
                    b.HasOne("HomeServices.Domain.Staff.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_refresh_tokens_staff_users_staff_user_id");
                });

            modelBuilder.Entity("HomeServices.Domain.Staff.StaffUserRole", b =>
                {
                    b.HasOne("HomeServices.Domain.Staff.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_user_role_roles_role_id");

                    b.HasOne("HomeServices.Domain.Staff.StaffUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_user_role_staff_users_staff_user_id");
                });

            modelBuilder.Entity("HomeServices.Domain.Catalog.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("HomeServices.Domain.Staff.StaffUser", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
